CREATE SCHEMA IF NOT EXISTS pgl_validate;

CREATE TABLE pgl_validate.peer (
    name                    text PRIMARY KEY,
    dsn                     text NOT NULL,
    backend                 text NOT NULL DEFAULT 'pglogical'
                            CHECK (backend IN ('pglogical','native','standby')),
    subscription_name       name,
    reverse_subscription_name name,
    replication_sets        text[],
    connect_timeout_seconds int NOT NULL DEFAULT 10
                            CHECK (connect_timeout_seconds > 0),
    statement_timeout_ms    int NOT NULL DEFAULT 600000
                            CHECK (statement_timeout_ms > 0),
    lock_timeout_ms         int NOT NULL DEFAULT 30000
                            CHECK (lock_timeout_ms > 0),
    added_at                timestamptz NOT NULL DEFAULT now()
);
REVOKE ALL ON pgl_validate.peer FROM PUBLIC;

CREATE TABLE pgl_validate.run (
    run_id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    status         text NOT NULL CHECK (status IN
                   ('planning','fencing','running','paused','rechecking',
                    'completed','failed','canceled')),
    options        jsonb NOT NULL DEFAULT '{}',
    reference_node text,
    launched_by    name NOT NULL DEFAULT current_user,
    started_at     timestamptz NOT NULL DEFAULT now(),
    finished_at    timestamptz,
    tables_total   int,
    tables_matched int,
    tables_differ  int,
    error          text
);

CREATE TABLE pgl_validate.run_participant (
    run_id     bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    node       text NOT NULL,
    role       text NOT NULL CHECK (role IN ('coordinator','reference','participant')),
    backend    text NOT NULL CHECK (backend IN ('pglogical','native','standby')),
    pg_version int  NOT NULL,
    dsn_ref    text,
    status     text NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','connected','converged','skipped','unreachable','done','error')),
    PRIMARY KEY (run_id, node)
);

CREATE TABLE pgl_validate.fence_epoch (
    run_id     bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    epoch_seq  int NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, epoch_seq)
);

CREATE TABLE pgl_validate.run_edge (
    run_id        bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    edge_id       int NOT NULL,
    provider_node text NOT NULL,
    target_node   text NOT NULL,
    backend       text NOT NULL CHECK (backend IN ('pglogical','native','standby')),
    subscription  text,
    slot_name     text,
    origin_name   text,
    repsets       text[],
    PRIMARY KEY (run_id, edge_id)
);

CREATE TABLE pgl_validate.fence_edge (
    run_id          bigint NOT NULL,
    epoch_seq       int NOT NULL,
    edge_id         int NOT NULL,
    fence_kind      text NOT NULL CHECK (fence_kind IN ('barrier','standby_replay','degraded')),
    barrier_token   uuid,
    barrier_end_lsn pg_lsn,
    PRIMARY KEY (run_id, epoch_seq, edge_id),
    CONSTRAINT fence_edge_required CHECK (
        (fence_kind = 'barrier'        AND barrier_token IS NOT NULL AND barrier_end_lsn IS NOT NULL) OR
        (fence_kind = 'standby_replay' AND barrier_token IS NULL     AND barrier_end_lsn IS NOT NULL) OR
        (fence_kind = 'degraded')
    ),
    FOREIGN KEY (run_id, epoch_seq) REFERENCES pgl_validate.fence_epoch(run_id, epoch_seq) ON DELETE CASCADE,
    FOREIGN KEY (run_id, edge_id) REFERENCES pgl_validate.run_edge(run_id, edge_id) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.fence_attempt (
    run_id              bigint NOT NULL,
    epoch_seq           int NOT NULL,
    edge_id             int NOT NULL,
    barrier_end_lsn     pg_lsn,
    origin_progress_lsn pg_lsn,
    token_visible       boolean NOT NULL DEFAULT false,
    confirmed_flush_lsn pg_lsn,
    converged_at        timestamptz,
    status              text NOT NULL DEFAULT 'waiting'
                        CHECK (status IN ('waiting','converged','timeout','degraded')),
    CONSTRAINT fence_attempt_converged_truth CHECK (
        status <> 'converged'
        OR (barrier_end_lsn IS NOT NULL
            AND origin_progress_lsn IS NOT NULL
            AND origin_progress_lsn >= barrier_end_lsn
            AND token_visible)
    ),
    PRIMARY KEY (run_id, epoch_seq, edge_id),
    FOREIGN KEY (run_id, epoch_seq, edge_id)
        REFERENCES pgl_validate.fence_edge(run_id, epoch_seq, edge_id) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.fence_barrier (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    token       uuid NOT NULL,
    injected_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX fence_barrier_token_idx ON pgl_validate.fence_barrier (token);

CREATE TABLE pgl_validate.fence_barrier_run (
    token           uuid NOT NULL,
    run_id          bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    epoch_seq       int NOT NULL,
    edge_id         int NOT NULL,
    origin_node     text NOT NULL,
    barrier_end_lsn pg_lsn,
    PRIMARY KEY (run_id, epoch_seq, edge_id),
    FOREIGN KEY (run_id, edge_id) REFERENCES pgl_validate.run_edge(run_id, edge_id) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.table_plan (
    run_id             bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    schema_name        text NOT NULL,
    table_name         text NOT NULL,
    key_cols           text[],
    att_list           text[],
    repsets            text[],
    repl_insert        boolean,
    repl_update        boolean,
    repl_delete        boolean,
    repl_truncate      boolean,
    has_row_filter     boolean NOT NULL DEFAULT false,
    sync_status        "char",
    validated_property text NOT NULL
                       CHECK (validated_property IN ('full','superset','keys_only',
                              'filtered_intersection','filtered_advisory','keyless',
                              'unsupported_mask','skipped')),
    PRIMARY KEY (run_id, schema_name, table_name)
);

CREATE TABLE pgl_validate.table_result (
    run_id      bigint NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    verdict     text NOT NULL CHECK (verdict IN
                ('match','differ','indeterminate','partial','approximate',
                 'degraded','skipped','error','fence_timeout')),
    reason      text,
    started_at  timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    PRIMARY KEY (run_id, schema_name, table_name),
    FOREIGN KEY (run_id, schema_name, table_name)
        REFERENCES pgl_validate.table_plan(run_id, schema_name, table_name) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.table_node_result (
    run_id      bigint NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    node        text NOT NULL,
    n_rows      bigint,
    lthash      bytea,
    set_hash    bytea,
    PRIMARY KEY (run_id, schema_name, table_name, node),
    FOREIGN KEY (run_id, schema_name, table_name)
        REFERENCES pgl_validate.table_plan(run_id, schema_name, table_name) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.chunk_result (
    run_id      bigint NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    chunk_id    bigint NOT NULL,
    parent_id   bigint,
    lo          bytea,
    hi          bytea,
    state       text NOT NULL CHECK (state IN
                ('pending','running','clean','split','divergent','candidate')),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, schema_name, table_name, chunk_id),
    FOREIGN KEY (run_id, schema_name, table_name)
        REFERENCES pgl_validate.table_plan(run_id, schema_name, table_name) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.chunk_node_result (
    run_id      bigint NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    chunk_id    bigint NOT NULL,
    node        text NOT NULL,
    n_rows      bigint,
    lthash      bytea,
    PRIMARY KEY (run_id, schema_name, table_name, chunk_id, node),
    FOREIGN KEY (run_id, schema_name, table_name, chunk_id)
        REFERENCES pgl_validate.chunk_result(run_id, schema_name, table_name, chunk_id)
        ON DELETE CASCADE
);

CREATE TABLE pgl_validate.divergence (
    run_id         bigint NOT NULL,
    schema_name    text NOT NULL,
    table_name     text NOT NULL,
    key_text       text NOT NULL,
    key_bytes      bytea NOT NULL,
    classification text NOT NULL CHECK (classification IN ('missing_on','extra_on','differs')),
    node           text NOT NULL,
    status         text NOT NULL DEFAULT 'candidate'
                   CHECK (status IN ('candidate','confirmed','cleared','indeterminate','advisory')),
    detected_epoch int NOT NULL,
    tuple          jsonb,
    detected_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, schema_name, table_name, key_bytes, node),
    FOREIGN KEY (run_id, schema_name, table_name)
        REFERENCES pgl_validate.table_plan(run_id, schema_name, table_name) ON DELETE CASCADE,
    FOREIGN KEY (run_id, detected_epoch)
        REFERENCES pgl_validate.fence_epoch(run_id, epoch_seq)
);

CREATE TABLE pgl_validate.divergence_recheck (
    run_id      bigint NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    key_bytes   bytea NOT NULL,
    node        text NOT NULL,
    epoch_seq   int NOT NULL,
    outcome     text NOT NULL CHECK (outcome IN ('still_differs','cleared','still_hot')),
    at          timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, schema_name, table_name, key_bytes, node, epoch_seq),
    FOREIGN KEY (run_id, schema_name, table_name, key_bytes, node)
        REFERENCES pgl_validate.divergence(run_id, schema_name, table_name, key_bytes, node)
        ON DELETE CASCADE
);

CREATE TABLE pgl_validate.conflict_evidence (
    run_id               bigint NOT NULL,
    schema_name          text NOT NULL,
    table_name           text NOT NULL,
    key_bytes            bytea NOT NULL,
    node                 text NOT NULL,
    source               text NOT NULL DEFAULT 'pglogical_conflict_history'
                         CHECK (source IN ('pglogical_conflict_history')),
    conflict_id          bigint NOT NULL,
    recorded_at          timestamptz NOT NULL,
    subscription_name    text,
    conflict_type        text NOT NULL,
    resolution           text NOT NULL,
    index_name           text,
    local_tuple          jsonb,
    local_xid            text,
    local_origin         integer,
    local_commit_ts      timestamptz,
    remote_tuple         jsonb,
    remote_origin        integer NOT NULL,
    remote_commit_ts     timestamptz NOT NULL,
    remote_commit_lsn    pg_lsn NOT NULL,
    has_before_triggers  boolean NOT NULL,
    matched_on           text[] NOT NULL DEFAULT ARRAY[]::text[],
    observed_at          timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (
        run_id, schema_name, table_name, key_bytes, node,
        source, recorded_at, conflict_id
    ),
    FOREIGN KEY (run_id, schema_name, table_name, key_bytes, node)
        REFERENCES pgl_validate.divergence(run_id, schema_name, table_name, key_bytes, node)
        ON DELETE CASCADE
);

CREATE TABLE pgl_validate.sequence_result (
    run_id                bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    schema_name           text NOT NULL,
    seq_name              text NOT NULL,
    provider_node         text NOT NULL,
    provider_last_value   bigint,
    subscriber_node       text NOT NULL,
    subscriber_last_value bigint,
    cache_size            int,
    within_contract       boolean,
    verdict               text NOT NULL CHECK (verdict IN ('match','behind','ahead_of_window','error')),
    PRIMARY KEY (run_id, schema_name, seq_name, subscriber_node)
);

CREATE TABLE pgl_validate.schema_issue (
    run_id      bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    node        text NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    issue_code  text NOT NULL,
    detail      text,
    PRIMARY KEY (run_id, node, schema_name, table_name, issue_code)
);

CREATE TABLE pgl_validate.schedule (
    name        text PRIMARY KEY,
    cron        text NOT NULL,
    tables      text[],
    repset      text,
    peers       text[],
    options     jsonb NOT NULL DEFAULT '{}',
    enabled     boolean NOT NULL DEFAULT true,
    last_run_id bigint REFERENCES pgl_validate.run(run_id) ON DELETE SET NULL
);

CREATE TABLE pgl_validate.worker_task (
    task_id       integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    run_id        bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    task_kind     text NOT NULL CHECK (task_kind IN ('compare')),
    request       jsonb NOT NULL,
    status        text NOT NULL DEFAULT 'queued'
                  CHECK (status IN ('queued','starting','running','completed','failed','canceled')),
    launched_by   name NOT NULL DEFAULT current_user,
    database_name name NOT NULL DEFAULT current_database(),
    worker_pid    integer,
    enqueued_at   timestamptz NOT NULL DEFAULT now(),
    started_at    timestamptz,
    finished_at   timestamptz,
    error         text
);
CREATE INDEX worker_task_run_idx ON pgl_validate.worker_task (run_id);
CREATE INDEX worker_task_active_idx ON pgl_validate.worker_task (status, enqueued_at)
WHERE status IN ('queued','starting','running');

CREATE TABLE pgl_validate.repair_run (
    repair_id      bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    run_id         bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    authoritative  text NOT NULL,
    target         text NOT NULL,
    propagation    text NOT NULL CHECK (propagation IN ('local_only','replicate')),
    paused_subs    text[],
    origin_name    text,
    status         text NOT NULL DEFAULT 'running'
                   CHECK (status IN ('running','applied','revalidated','failed','rolled_back')),
    launched_by    name NOT NULL DEFAULT current_user,
    started_at     timestamptz NOT NULL DEFAULT now(),
    finished_at    timestamptz,
    error          text
);

CREATE TABLE pgl_validate.repair_result (
    repair_id      bigint NOT NULL REFERENCES pgl_validate.repair_run(repair_id) ON DELETE CASCADE,
    schema_name    text NOT NULL,
    table_name     text NOT NULL,
    key_bytes      bytea NOT NULL,
    action         text NOT NULL CHECK (action IN ('insert','update','delete','setval')),
    statement      text NOT NULL,
    post_verdict   text CHECK (post_verdict IN ('match','still_differs','indeterminate')),
    PRIMARY KEY (repair_id, schema_name, table_name, key_bytes, action)
);

CREATE OR REPLACE VIEW pgl_validate.runs AS
SELECT * FROM pgl_validate.run;

CREATE OR REPLACE VIEW pgl_validate.table_results AS
SELECT * FROM pgl_validate.table_result;

CREATE OR REPLACE VIEW pgl_validate.chunk_results AS
SELECT * FROM pgl_validate.chunk_result;

CREATE OR REPLACE VIEW pgl_validate.divergences AS
SELECT * FROM pgl_validate.divergence;

CREATE OR REPLACE VIEW pgl_validate.sequence_results AS
SELECT * FROM pgl_validate.sequence_result;

CREATE OR REPLACE VIEW pgl_validate.schema_issues AS
SELECT * FROM pgl_validate.schema_issue;

CREATE OR REPLACE VIEW pgl_validate.worker_tasks AS
SELECT * FROM pgl_validate.worker_task;

CREATE OR REPLACE VIEW pgl_validate.run_progress AS
WITH chunk_counts AS (
    SELECT
        cr.run_id,
        count(cr.*) FILTER (WHERE cr.state IN ('clean','divergent')) AS chunks_done,
        count(cr.*) FILTER (WHERE cr.state <> 'split') AS chunks_total
    FROM pgl_validate.chunk_result cr
    GROUP BY cr.run_id
),
chunk_scan AS (
    SELECT
        cnr.run_id,
        COALESCE(sum(cnr.n_rows), 0)::bigint AS rows_scanned,
        COALESCE(sum(cnr.n_rows), 0)::bigint * 32 AS bytes_scanned
    FROM pgl_validate.chunk_node_result cnr
    GROUP BY cnr.run_id
),
table_progress AS (
    SELECT
        tnr.run_id,
        COALESCE(sum(tnr.n_rows), 0)::bigint AS rows_scanned,
        COALESCE(sum(tnr.n_rows), 0)::bigint * 32 AS bytes_scanned
    FROM pgl_validate.table_node_result tnr
    GROUP BY tnr.run_id
),
epoch_progress AS (
    SELECT
        fe.run_id,
        max(fe.epoch_seq) AS current_epoch
    FROM pgl_validate.fence_epoch fe
    GROUP BY fe.run_id
),
fence_progress AS (
    SELECT
        fa.run_id,
        bool_or(fa.status = 'waiting') AS has_waiting_fence
    FROM pgl_validate.fence_attempt fa
    GROUP BY fa.run_id
),
divergence_progress AS (
    SELECT
        d.run_id,
        bool_or(d.status = 'candidate') AS has_candidate_divergence
    FROM pgl_validate.divergence d
    GROUP BY d.run_id
)
SELECT
    r.run_id,
    r.status,
    CASE
        WHEN r.status IN ('completed','failed','canceled','paused') THEN r.status
        WHEN COALESCE(fp.has_waiting_fence, false) THEN 'fencing'
        WHEN COALESCE(dp.has_candidate_divergence, false) THEN 'rechecking'
        WHEN r.status = 'running' THEN 'running'
        ELSE r.status
    END AS phase,
    ep.current_epoch,
    COALESCE(cc.chunks_done, 0)::bigint AS chunks_done,
    COALESCE(cc.chunks_total, 0)::bigint AS chunks_total,
    (COALESCE(cs.rows_scanned, 0) + COALESCE(tp.rows_scanned, 0))::bigint AS rows_scanned,
    (COALESCE(cs.bytes_scanned, 0) + COALESCE(tp.bytes_scanned, 0))::bigint AS bytes_scanned,
    CASE
        WHEN r.status IN ('completed','failed','canceled')
          OR r.started_at IS NULL
          OR COALESCE(cc.chunks_done, 0) <= 0
          OR COALESCE(cc.chunks_total, 0) <= COALESCE(cc.chunks_done, 0)
        THEN NULL::interval
        ELSE make_interval(secs => (
            extract(epoch FROM (clock_timestamp() - r.started_at))
            * (COALESCE(cc.chunks_total, 0) - COALESCE(cc.chunks_done, 0))::double precision
            / COALESCE(cc.chunks_done, 0)::double precision
        ))
    END AS eta,
    r.started_at,
    r.finished_at
FROM pgl_validate.run r
LEFT JOIN chunk_counts cc USING (run_id)
LEFT JOIN chunk_scan cs USING (run_id)
LEFT JOIN table_progress tp USING (run_id)
LEFT JOIN epoch_progress ep USING (run_id)
LEFT JOIN fence_progress fp USING (run_id)
LEFT JOIN divergence_progress dp USING (run_id);

