CREATE SCHEMA IF NOT EXISTS pgl_validate;

CREATE TABLE pgl_validate.peer (
    name                    text PRIMARY KEY,
    dsn                     text NOT NULL,
    backend                 text NOT NULL DEFAULT 'pglogical'
                            CHECK (backend IN ('pglogical','native','standby')),
    subscription_name       name,
    replication_sets        text[],
    connect_timeout_seconds int NOT NULL DEFAULT 10
                            CHECK (connect_timeout_seconds > 0),
    statement_timeout_ms    int NOT NULL DEFAULT 600000
                            CHECK (statement_timeout_ms > 0),
    lock_timeout_ms         int NOT NULL DEFAULT 30000
                            CHECK (lock_timeout_ms > 0),
    added_at                timestamptz NOT NULL DEFAULT now()
);
REVOKE ALL ON pgl_validate.peer FROM PUBLIC;

CREATE TABLE pgl_validate.run (
    run_id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    status         text NOT NULL CHECK (status IN
                   ('planning','fencing','running','paused','rechecking',
                    'completed','failed','canceled')),
    options        jsonb NOT NULL DEFAULT '{}',
    reference_node text,
    launched_by    name NOT NULL DEFAULT current_user,
    started_at     timestamptz NOT NULL DEFAULT now(),
    finished_at    timestamptz,
    tables_total   int,
    tables_matched int,
    tables_differ  int,
    error          text
);

CREATE TABLE pgl_validate.run_participant (
    run_id     bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    node       text NOT NULL,
    role       text NOT NULL CHECK (role IN ('coordinator','reference','participant')),
    backend    text NOT NULL CHECK (backend IN ('pglogical','native','standby')),
    pg_version int  NOT NULL,
    dsn_ref    text,
    status     text NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','connected','converged','unreachable','done','error')),
    PRIMARY KEY (run_id, node)
);

CREATE TABLE pgl_validate.fence_epoch (
    run_id     bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    epoch_seq  int NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, epoch_seq)
);

CREATE TABLE pgl_validate.run_edge (
    run_id        bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    edge_id       int NOT NULL,
    provider_node text NOT NULL,
    target_node   text NOT NULL,
    backend       text NOT NULL CHECK (backend IN ('pglogical','native','standby')),
    subscription  text,
    slot_name     text,
    origin_name   text,
    repsets       text[],
    PRIMARY KEY (run_id, edge_id)
);

CREATE TABLE pgl_validate.fence_edge (
    run_id          bigint NOT NULL,
    epoch_seq       int NOT NULL,
    edge_id         int NOT NULL,
    fence_kind      text NOT NULL CHECK (fence_kind IN ('barrier','standby_replay','degraded')),
    barrier_token   uuid,
    barrier_end_lsn pg_lsn,
    PRIMARY KEY (run_id, epoch_seq, edge_id),
    CONSTRAINT fence_edge_required CHECK (
        (fence_kind = 'barrier'        AND barrier_token IS NOT NULL AND barrier_end_lsn IS NOT NULL) OR
        (fence_kind = 'standby_replay' AND barrier_token IS NULL     AND barrier_end_lsn IS NOT NULL) OR
        (fence_kind = 'degraded')
    ),
    FOREIGN KEY (run_id, epoch_seq) REFERENCES pgl_validate.fence_epoch(run_id, epoch_seq) ON DELETE CASCADE,
    FOREIGN KEY (run_id, edge_id) REFERENCES pgl_validate.run_edge(run_id, edge_id) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.fence_attempt (
    run_id              bigint NOT NULL,
    epoch_seq           int NOT NULL,
    edge_id             int NOT NULL,
    barrier_end_lsn     pg_lsn,
    origin_progress_lsn pg_lsn,
    token_visible       boolean NOT NULL DEFAULT false,
    confirmed_flush_lsn pg_lsn,
    converged_at        timestamptz,
    status              text NOT NULL DEFAULT 'waiting'
                        CHECK (status IN ('waiting','converged','timeout','degraded')),
    CONSTRAINT fence_attempt_converged_truth CHECK (
        status <> 'converged'
        OR (barrier_end_lsn IS NOT NULL
            AND origin_progress_lsn IS NOT NULL
            AND origin_progress_lsn >= barrier_end_lsn
            AND token_visible)
    ),
    PRIMARY KEY (run_id, epoch_seq, edge_id),
    FOREIGN KEY (run_id, epoch_seq, edge_id)
        REFERENCES pgl_validate.fence_edge(run_id, epoch_seq, edge_id) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.fence_barrier (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    token       uuid NOT NULL,
    injected_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX fence_barrier_token_idx ON pgl_validate.fence_barrier (token);

CREATE TABLE pgl_validate.fence_barrier_run (
    token           uuid NOT NULL,
    run_id          bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    epoch_seq       int NOT NULL,
    edge_id         int NOT NULL,
    origin_node     text NOT NULL,
    barrier_end_lsn pg_lsn,
    PRIMARY KEY (run_id, epoch_seq, edge_id),
    FOREIGN KEY (run_id, edge_id) REFERENCES pgl_validate.run_edge(run_id, edge_id) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.table_plan (
    run_id             bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    schema_name        text NOT NULL,
    table_name         text NOT NULL,
    key_cols           text[],
    att_list           text[],
    repsets            text[],
    repl_insert        boolean,
    repl_update        boolean,
    repl_delete        boolean,
    repl_truncate      boolean,
    has_row_filter     boolean NOT NULL DEFAULT false,
    sync_status        "char",
    validated_property text NOT NULL
                       CHECK (validated_property IN ('full','superset','keys_only',
                              'filtered_intersection','filtered_advisory','keyless',
                              'unsupported_mask','skipped')),
    PRIMARY KEY (run_id, schema_name, table_name)
);

CREATE TABLE pgl_validate.table_result (
    run_id      bigint NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    verdict     text NOT NULL CHECK (verdict IN
                ('match','differ','indeterminate','partial','approximate',
                 'degraded','skipped','error','fence_timeout')),
    reason      text,
    started_at  timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    PRIMARY KEY (run_id, schema_name, table_name),
    FOREIGN KEY (run_id, schema_name, table_name)
        REFERENCES pgl_validate.table_plan(run_id, schema_name, table_name) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.table_node_result (
    run_id      bigint NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    node        text NOT NULL,
    n_rows      bigint,
    lthash      bytea,
    set_hash    bytea,
    PRIMARY KEY (run_id, schema_name, table_name, node),
    FOREIGN KEY (run_id, schema_name, table_name)
        REFERENCES pgl_validate.table_plan(run_id, schema_name, table_name) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.chunk_result (
    run_id      bigint NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    chunk_id    bigint NOT NULL,
    parent_id   bigint,
    lo          bytea,
    hi          bytea,
    state       text NOT NULL CHECK (state IN
                ('pending','running','clean','split','divergent','candidate')),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, schema_name, table_name, chunk_id),
    FOREIGN KEY (run_id, schema_name, table_name)
        REFERENCES pgl_validate.table_plan(run_id, schema_name, table_name) ON DELETE CASCADE
);

CREATE TABLE pgl_validate.chunk_node_result (
    run_id      bigint NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    chunk_id    bigint NOT NULL,
    node        text NOT NULL,
    n_rows      bigint,
    lthash      bytea,
    PRIMARY KEY (run_id, schema_name, table_name, chunk_id, node),
    FOREIGN KEY (run_id, schema_name, table_name, chunk_id)
        REFERENCES pgl_validate.chunk_result(run_id, schema_name, table_name, chunk_id)
        ON DELETE CASCADE
);

CREATE TABLE pgl_validate.divergence (
    run_id         bigint NOT NULL,
    schema_name    text NOT NULL,
    table_name     text NOT NULL,
    key_text       text NOT NULL,
    key_bytes      bytea NOT NULL,
    classification text NOT NULL CHECK (classification IN ('missing_on','extra_on','differs')),
    node           text NOT NULL,
    status         text NOT NULL DEFAULT 'candidate'
                   CHECK (status IN ('candidate','confirmed','cleared','indeterminate','advisory')),
    detected_epoch int NOT NULL,
    tuple          jsonb,
    detected_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, schema_name, table_name, key_bytes, node),
    FOREIGN KEY (run_id, schema_name, table_name)
        REFERENCES pgl_validate.table_plan(run_id, schema_name, table_name) ON DELETE CASCADE,
    FOREIGN KEY (run_id, detected_epoch)
        REFERENCES pgl_validate.fence_epoch(run_id, epoch_seq)
);

CREATE TABLE pgl_validate.divergence_recheck (
    run_id      bigint NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    key_bytes   bytea NOT NULL,
    node        text NOT NULL,
    epoch_seq   int NOT NULL,
    outcome     text NOT NULL CHECK (outcome IN ('still_differs','cleared','still_hot')),
    at          timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, schema_name, table_name, key_bytes, node, epoch_seq),
    FOREIGN KEY (run_id, schema_name, table_name, key_bytes, node)
        REFERENCES pgl_validate.divergence(run_id, schema_name, table_name, key_bytes, node)
        ON DELETE CASCADE
);

CREATE TABLE pgl_validate.sequence_result (
    run_id                bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    schema_name           text NOT NULL,
    seq_name              text NOT NULL,
    provider_node         text NOT NULL,
    provider_last_value   bigint,
    subscriber_node       text NOT NULL,
    subscriber_last_value bigint,
    cache_size            int,
    within_contract       boolean,
    verdict               text NOT NULL CHECK (verdict IN ('match','behind','ahead_of_window','error')),
    PRIMARY KEY (run_id, schema_name, seq_name, subscriber_node)
);

CREATE TABLE pgl_validate.schema_issue (
    run_id      bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    node        text NOT NULL,
    schema_name text NOT NULL,
    table_name  text NOT NULL,
    issue_code  text NOT NULL,
    detail      text,
    PRIMARY KEY (run_id, node, schema_name, table_name, issue_code)
);

CREATE TABLE pgl_validate.schedule (
    name        text PRIMARY KEY,
    cron        text NOT NULL,
    tables      text[],
    repset      text,
    peers       text[],
    options     jsonb NOT NULL DEFAULT '{}',
    enabled     boolean NOT NULL DEFAULT true,
    last_run_id bigint REFERENCES pgl_validate.run(run_id) ON DELETE SET NULL
);

CREATE TABLE pgl_validate.repair_run (
    repair_id      bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    run_id         bigint NOT NULL REFERENCES pgl_validate.run(run_id) ON DELETE CASCADE,
    authoritative  text NOT NULL,
    target         text NOT NULL,
    propagation    text NOT NULL CHECK (propagation IN ('local_only','replicate')),
    paused_subs    text[],
    origin_name    text,
    status         text NOT NULL DEFAULT 'running'
                   CHECK (status IN ('running','applied','revalidated','failed','rolled_back')),
    launched_by    name NOT NULL DEFAULT current_user,
    started_at     timestamptz NOT NULL DEFAULT now(),
    finished_at    timestamptz,
    error          text
);

CREATE TABLE pgl_validate.repair_result (
    repair_id      bigint NOT NULL REFERENCES pgl_validate.repair_run(repair_id) ON DELETE CASCADE,
    schema_name    text NOT NULL,
    table_name     text NOT NULL,
    key_bytes      bytea NOT NULL,
    action         text NOT NULL CHECK (action IN ('insert','update','delete','setval')),
    statement      text NOT NULL,
    post_verdict   text CHECK (post_verdict IN ('match','still_differs','indeterminate')),
    PRIMARY KEY (repair_id, schema_name, table_name, key_bytes, action)
);

CREATE OR REPLACE VIEW pgl_validate.runs AS
SELECT * FROM pgl_validate.run;

CREATE OR REPLACE VIEW pgl_validate.table_results AS
SELECT * FROM pgl_validate.table_result;

CREATE OR REPLACE VIEW pgl_validate.chunk_results AS
SELECT * FROM pgl_validate.chunk_result;

CREATE OR REPLACE VIEW pgl_validate.divergences AS
SELECT * FROM pgl_validate.divergence;

CREATE OR REPLACE VIEW pgl_validate.sequence_results AS
SELECT * FROM pgl_validate.sequence_result;

CREATE OR REPLACE VIEW pgl_validate.schema_issues AS
SELECT * FROM pgl_validate.schema_issue;

CREATE OR REPLACE VIEW pgl_validate.run_progress AS
SELECT
    r.run_id,
    r.status,
    count(cr.*) FILTER (WHERE cr.state IN ('clean','divergent')) AS chunks_done,
    count(cr.*) AS chunks_total,
    r.started_at,
    r.finished_at
FROM pgl_validate.run r
LEFT JOIN pgl_validate.chunk_result cr USING (run_id)
GROUP BY r.run_id, r.status, r.started_at, r.finished_at;

-- Pick the coordinator-pushed encoding mode for a column. This is intentionally
-- conservative for types whose binary send format is less suitable as a
-- cross-version contract; the coordinator emits the chosen mode positionally in
-- row_digest(enc[], VARIADIC "any").
CREATE FUNCTION pgl_validate.column_encoding_mode(type_oid oid)
RETURNS int
LANGUAGE sql
STABLE
AS $$
    SELECT CASE
        WHEN type_oid IN ('json'::regtype::oid, 'numeric'::regtype::oid) THEN 2
        WHEN t.typsend = 0 THEN 2
        ELSE 1
    END
    FROM pg_type t
    WHERE t.oid = type_oid
$$;

-- Resolve the pglogical replication contract for one relation. The effective
-- column list is taken from pglogical.show_repset_table_info(), because that is
-- pglogical's own resolved bitmap after combining all covering repsets.
CREATE FUNCTION pgl_validate.pglogical_table_contract(
    relation regclass,
    input_repsets text[] DEFAULT NULL,
    subscription_name name DEFAULT NULL
)
RETURNS TABLE (
    schema_name text,
    table_name text,
    key_cols text[],
    att_list text[],
    repsets text[],
    repl_insert boolean,
    repl_update boolean,
    repl_delete boolean,
    repl_truncate boolean,
    has_row_filter boolean,
    row_filter_sql text,
    row_filter_exact boolean,
    sync_status "char",
    validated_property text,
    exact_comparable boolean,
    reason text
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    info record;
    action_rec record;
    filter_rec record;
    status_text text;
BEGIN
    IF to_regprocedure('pglogical.show_repset_table_info(regclass,text[])') IS NULL THEN
        RAISE EXCEPTION 'pglogical extension is not installed in this database'
            USING ERRCODE = '0A000';
    END IF;

    SELECT n.nspname, c.relname
    INTO schema_name, table_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.oid = relation;

    SELECT array_agg(a.attname ORDER BY ord.ordinality)
    INTO key_cols
    FROM pg_index i
    CROSS JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS ord(attnum, ordinality)
    JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ord.attnum
    WHERE i.indrelid = relation
      AND i.indisprimary;

    IF input_repsets IS NULL OR cardinality(input_repsets) = 0 THEN
        SELECT array_agg(DISTINCT rs.set_name::text ORDER BY rs.set_name::text)
        INTO repsets
        FROM pglogical.replication_set_table rst
        JOIN pglogical.replication_set rs ON rs.set_id = rst.set_id
        WHERE rst.set_reloid = relation;
    ELSE
        SELECT array_agg(DISTINCT requested.repset ORDER BY requested.repset)
        INTO repsets
        FROM unnest(input_repsets) AS requested(repset);
    END IF;

    IF repsets IS NULL OR cardinality(repsets) = 0 THEN
        att_list := NULL;
        repl_insert := false;
        repl_update := false;
        repl_delete := false;
        repl_truncate := false;
        has_row_filter := false;
        row_filter_sql := NULL;
        row_filter_exact := true;
        sync_status := NULL;
        validated_property := 'skipped';
        exact_comparable := false;
        reason := 'table is not a member of any selected pglogical replication set';
        RETURN NEXT;
        RETURN;
    END IF;

    SELECT *
    INTO info
    FROM pglogical.show_repset_table_info(relation, repsets);

    att_list := info.att_list;
    IF att_list IS NULL OR cardinality(att_list) = 0 THEN
        SELECT array_agg(a.attname ORDER BY a.attname)
        INTO att_list
        FROM pg_attribute a
        WHERE a.attrelid = relation
          AND a.attnum > 0
          AND NOT a.attisdropped;
    END IF;

    SELECT bool_or(rs.replicate_insert) AS repl_insert,
           bool_or(rs.replicate_update) AS repl_update,
           bool_or(rs.replicate_delete) AS repl_delete,
           bool_or(rs.replicate_truncate) AS repl_truncate
    INTO action_rec
    FROM pglogical.replication_set rs
    WHERE rs.set_name::text = ANY (repsets);

    repl_insert := COALESCE(action_rec.repl_insert, false);
    repl_update := COALESCE(action_rec.repl_update, false);
    repl_delete := COALESCE(action_rec.repl_delete, false);
    repl_truncate := COALESCE(action_rec.repl_truncate, false);

    SELECT
        COALESCE(bool_or(rst.set_row_filter IS NULL), false) AS has_unfiltered_membership,
        count(*) FILTER (WHERE rst.set_row_filter IS NOT NULL) AS filtered_memberships,
        string_agg(
            format('(%s)', pg_get_expr(rst.set_row_filter, rst.set_reloid)),
            ' OR '
            ORDER BY rs.set_name::text
        ) FILTER (WHERE rst.set_row_filter IS NOT NULL) AS predicate,
        bool_and(
            pgl_validate.row_filter_tree_is_immutable(rst.set_row_filter::text)
            AND pg_get_expr(rst.set_row_filter, rst.set_reloid) !~*
                '(^|[^[:alnum:]_])(current_user|session_user|current_role|current_setting|set_config|current_schema|current_schemas)([^[:alnum:]_]|$)'
        ) FILTER (WHERE rst.set_row_filter IS NOT NULL) AS exact
    INTO filter_rec
    FROM pglogical.replication_set_table rst
    JOIN pglogical.replication_set rs ON rs.set_id = rst.set_id
    WHERE rst.set_reloid = relation
      AND rs.set_name::text = ANY (repsets);

    IF COALESCE(filter_rec.has_unfiltered_membership, false)
       OR COALESCE(filter_rec.filtered_memberships, 0) = 0 THEN
        has_row_filter := false;
        row_filter_sql := NULL;
        row_filter_exact := true;
    ELSE
        has_row_filter := true;
        row_filter_sql := filter_rec.predicate;
        row_filter_exact := COALESCE(filter_rec.exact, false);
    END IF;

    sync_status := 'r';
    IF subscription_name IS NOT NULL THEN
        SELECT s.status
        INTO status_text
        FROM pglogical.show_subscription_table(subscription_name, relation) AS s;

        IF status_text IS NOT NULL THEN
            sync_status := left(status_text, 1)::"char";
        END IF;
    ELSE
        SELECT lss.sync_status
        INTO sync_status
        FROM pglogical.local_sync_status lss
        WHERE lss.sync_nspname = schema_name::name
          AND lss.sync_relname = table_name::name
        ORDER BY lss.sync_statuslsn DESC
        LIMIT 1;

        sync_status := COALESCE(sync_status, 'r');
    END IF;

    IF sync_status <> 'r' THEN
        validated_property := 'skipped';
        exact_comparable := false;
        reason := format('pglogical sync status is %s, not ready', sync_status);
    ELSIF NOT repl_insert THEN
        validated_property := 'unsupported_mask';
        exact_comparable := false;
        reason := 'replicate_insert=false means the provider row set does not bound the subscriber';
    ELSIF has_row_filter AND repl_update AND row_filter_exact THEN
        validated_property := 'filtered_intersection';
        exact_comparable := true;
        reason := 'pglogical row filter is immutable/context-free; validating content intersection with advisory presence differences';
    ELSIF has_row_filter AND repl_update THEN
        validated_property := 'skipped';
        exact_comparable := false;
        reason := 'pglogical row filter is not immutable/context-free; exact validation would be session-sensitive';
    ELSIF has_row_filter THEN
        validated_property := 'filtered_advisory';
        exact_comparable := false;
        reason := 'pglogical filtered table without update replication is advisory only';
    ELSIF repl_update AND repl_delete AND repl_truncate THEN
        validated_property := 'full';
        exact_comparable := true;
        reason := 'full pglogical action mask with no row filter';
    ELSIF repl_update THEN
        validated_property := 'superset';
        exact_comparable := true;
        reason := 'delete or truncate is not replicated, so subscriber extras are legitimate';
    ELSE
        validated_property := 'keys_only';
        exact_comparable := true;
        reason := 'updates are not replicated, so content drift is contract-permitted';
    END IF;

    RETURN NEXT;
END
$$;

-- Ensure the dedicated insert-only barrier replication set exists on the
-- current pglogical node and carries only the standalone barrier table.
CREATE FUNCTION pgl_validate.ensure_pglogical_barrier_repset()
RETURNS void
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
    set_rec record;
    table_member boolean;
BEGIN
    IF to_regprocedure('pglogical.create_replication_set(name,boolean,boolean,boolean,boolean)') IS NULL THEN
        RAISE EXCEPTION 'pglogical extension is not installed in this database'
            USING ERRCODE = '0A000';
    END IF;

    SELECT rs.*
    INTO set_rec
    FROM pglogical.replication_set rs
    JOIN pglogical.local_node ln ON ln.node_id = rs.set_nodeid
    WHERE rs.set_name = 'pgl_validate_barrier'::name;

    IF NOT FOUND THEN
        PERFORM pglogical.create_replication_set(
            'pgl_validate_barrier'::name,
            true,
            false,
            false,
            false
        );
    ELSIF NOT (
        set_rec.replicate_insert
        AND NOT set_rec.replicate_update
        AND NOT set_rec.replicate_delete
        AND NOT set_rec.replicate_truncate
    ) THEN
        RAISE EXCEPTION
            'pglogical replication set pgl_validate_barrier exists but is not insert-only';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pglogical.replication_set rs
        JOIN pglogical.local_node ln ON ln.node_id = rs.set_nodeid
        JOIN pglogical.replication_set_table rst ON rst.set_id = rs.set_id
        WHERE rs.set_name = 'pgl_validate_barrier'::name
          AND rst.set_reloid <> 'pgl_validate.fence_barrier'::regclass
    ) THEN
        RAISE EXCEPTION
            'pglogical replication set pgl_validate_barrier must contain only pgl_validate.fence_barrier';
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM pglogical.replication_set rs
        JOIN pglogical.local_node ln ON ln.node_id = rs.set_nodeid
        JOIN pglogical.replication_set_table rst ON rst.set_id = rs.set_id
        WHERE rs.set_name = 'pgl_validate_barrier'::name
          AND rst.set_reloid = 'pgl_validate.fence_barrier'::regclass
    )
    INTO table_member;

    IF NOT table_member THEN
        PERFORM pglogical.replication_set_add_table(
            'pgl_validate_barrier'::name,
            'pgl_validate.fence_barrier'::regclass,
            false
        );
    END IF;
END
$$;

-- Fence one pglogical provider->target edge by injecting a real replicated
-- barrier, waiting for provider-side slot flush, then polling target-side
-- origin progress and token visibility until convergence or timeout.
CREATE FUNCTION pgl_validate.fence_pglogical_edge(
    p_run_id bigint,
    p_epoch_seq int,
    p_edge_id int,
    p_provider_node text,
    p_target_node text,
    p_provider_dsn text,
    p_target_dsn text,
    p_subscription_name text,
    p_slot_name text,
    p_origin_name text,
    p_repsets text[] DEFAULT ARRAY['pgl_validate_barrier']::text[],
    p_connect_timeout_seconds int DEFAULT 10,
    p_statement_timeout_ms int DEFAULT 600000,
    p_lock_timeout_ms int DEFAULT 30000,
    p_fence_timeout_ms int DEFAULT 300000,
    p_poll_interval_ms int DEFAULT 100
)
RETURNS pgl_validate.fence_attempt
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
    injection record;
    confirmed_flush_lsn pg_lsn;
    observation record;
    deadline timestamptz;
    attempt_status text;
    result_row pgl_validate.fence_attempt;
BEGIN
    IF p_run_id IS NULL THEN
        RAISE EXCEPTION 'run_id is required';
    END IF;
    IF p_epoch_seq IS NULL THEN
        RAISE EXCEPTION 'epoch_seq is required';
    END IF;
    IF p_edge_id IS NULL THEN
        RAISE EXCEPTION 'edge_id is required';
    END IF;
    IF p_provider_node IS NULL OR p_target_node IS NULL THEN
        RAISE EXCEPTION 'provider_node and target_node are required';
    END IF;
    IF p_provider_dsn IS NULL OR p_target_dsn IS NULL THEN
        RAISE EXCEPTION 'provider_dsn and target_dsn are required';
    END IF;
    IF p_slot_name IS NULL THEN
        RAISE EXCEPTION 'slot_name is required';
    END IF;
    IF p_origin_name IS NULL THEN
        RAISE EXCEPTION 'origin_name is required';
    END IF;
    IF p_fence_timeout_ms <= 0 THEN
        RAISE EXCEPTION 'fence_timeout_ms must be greater than zero';
    END IF;
    IF p_poll_interval_ms <= 0 THEN
        RAISE EXCEPTION 'poll_interval_ms must be greater than zero';
    END IF;

    INSERT INTO pgl_validate.run_edge(
        run_id, edge_id, provider_node, target_node, backend,
        subscription, slot_name, origin_name, repsets
    )
    VALUES (
        p_run_id, p_edge_id, p_provider_node, p_target_node, 'pglogical',
        p_subscription_name, p_slot_name, p_origin_name, p_repsets
    )
    ON CONFLICT (run_id, edge_id) DO UPDATE
    SET provider_node = EXCLUDED.provider_node,
        target_node = EXCLUDED.target_node,
        backend = 'pglogical',
        subscription = EXCLUDED.subscription,
        slot_name = EXCLUDED.slot_name,
        origin_name = EXCLUDED.origin_name,
        repsets = EXCLUDED.repsets;

    SELECT *
    INTO injection
    FROM pgl_validate.remote_inject_barrier(
        p_provider_dsn,
        p_connect_timeout_seconds,
        p_statement_timeout_ms,
        p_lock_timeout_ms
    );

    PERFORM pgl_validate.record_barrier_fence(
        p_run_id,
        p_epoch_seq,
        p_edge_id,
        injection.token,
        p_provider_node,
        injection.barrier_end_lsn
    );

    SELECT pgl_validate.remote_wait_slot_confirm_lsn(
        p_provider_dsn,
        p_slot_name,
        injection.barrier_end_lsn,
        p_connect_timeout_seconds,
        p_statement_timeout_ms,
        p_lock_timeout_ms
    )
    INTO confirmed_flush_lsn;

    IF confirmed_flush_lsn < injection.barrier_end_lsn THEN
        RAISE EXCEPTION
            'slot % confirmed_flush_lsn % is behind barrier_end_lsn %',
            p_slot_name,
            confirmed_flush_lsn,
            injection.barrier_end_lsn;
    END IF;

    deadline := clock_timestamp() + make_interval(secs => p_fence_timeout_ms / 1000.0);
    LOOP
        SELECT *
        INTO observation
        FROM pgl_validate.remote_observe_barrier(
            p_target_dsn,
            p_origin_name,
            injection.token,
            injection.barrier_end_lsn,
            p_connect_timeout_seconds,
            p_statement_timeout_ms,
            p_lock_timeout_ms
        );

        EXIT WHEN observation.converged;

        IF clock_timestamp() >= deadline THEN
            attempt_status := 'timeout';
            EXIT;
        END IF;

        PERFORM pg_sleep(p_poll_interval_ms / 1000.0);
    END LOOP;

    SELECT *
    INTO result_row
    FROM pgl_validate.record_fence_attempt(
        p_run_id,
        p_epoch_seq,
        p_edge_id,
        injection.barrier_end_lsn,
        observation.origin_progress_lsn,
        observation.token_visible,
        confirmed_flush_lsn,
        attempt_status
    );

    RETURN result_row;
END
$$;

-- Generate the planner-visible SQL used to checksum a table chunk. Columns are
-- sorted by name before they are passed as heterogeneous VARIADIC row_digest
-- arguments; callers may EXPLAIN the returned SQL directly on a participant.
CREATE FUNCTION pgl_validate.plan_chunk_sql(
    rel regclass,
    key_cols text[],
    lo bytea,
    hi bytea,
    cols text[],
    repsets text[] DEFAULT NULL,
    row_filter_sql text DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    rel_sql text;
    enc_modes int[];
    digest_args text;
    selected_cols text[];
BEGIN
    IF lo IS NOT NULL OR hi IS NOT NULL THEN
        RAISE EXCEPTION 'bounded chunks are not available until Merkle planning is enabled'
            USING ERRCODE = '0A000';
    END IF;

    SELECT format('%I.%I', n.nspname, c.relname)
    INTO rel_sql
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.oid = rel;

    IF rel_sql IS NULL THEN
        RAISE EXCEPTION 'relation % does not exist', rel;
    END IF;

    IF cols IS NULL OR cardinality(cols) = 0 THEN
        SELECT array_agg(a.attname ORDER BY a.attname)
        INTO selected_cols
        FROM pg_attribute a
        WHERE a.attrelid = rel
          AND a.attnum > 0
          AND NOT a.attisdropped;
    ELSE
        SELECT array_agg(a.attname ORDER BY a.attname)
        INTO selected_cols
        FROM unnest(cols) requested(col_name)
        JOIN pg_attribute a
          ON a.attrelid = rel
         AND a.attname = requested.col_name
         AND a.attnum > 0
         AND NOT a.attisdropped;

        IF cardinality(selected_cols) IS DISTINCT FROM cardinality(cols) THEN
            RAISE EXCEPTION 'one or more requested columns are not present on %', rel::text;
        END IF;
    END IF;

    IF selected_cols IS NULL OR cardinality(selected_cols) = 0 THEN
        RAISE EXCEPTION 'no comparable columns found on %', rel::text;
    END IF;

    SELECT
        array_agg(pgl_validate.column_encoding_mode(a.atttypid) ORDER BY a.attname),
        string_agg(format('t.%I', a.attname), ', ' ORDER BY a.attname)
    INTO enc_modes, digest_args
    FROM pg_attribute a
    WHERE a.attrelid = rel
      AND a.attname = ANY (selected_cols)
      AND a.attnum > 0
      AND NOT a.attisdropped;

    RETURN format(
        'SELECT count(*)::bigint AS n_rows, pgl_validate.lthash_bytes(pgl_validate.lthash(pgl_validate.row_digest(%L::int[], %s))) AS lthash FROM %s t WHERE %s',
        enc_modes::text,
        digest_args,
        rel_sql,
        CASE
            WHEN row_filter_sql IS NULL OR btrim(row_filter_sql) = '' THEN 'true'
            ELSE format('(%s)', row_filter_sql)
        END
    );
END
$$;

-- Generate the planner-visible SQL used to enumerate keys and row digests for
-- a localized divergent range. The current implementation emits the whole
-- relation; range predicates will reuse this shape once Merkle bounds exist.
CREATE FUNCTION pgl_validate.plan_localize_sql(
    rel regclass,
    key_cols text[],
    cols text[],
    row_filter_sql text DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    rel_sql text;
    selected_cols text[];
    selected_key_cols text[];
    enc_modes int[];
    key_enc_modes int[];
    digest_args text;
    key_digest_args text;
    key_text_args text;
    order_args text;
BEGIN
    IF key_cols IS NULL OR cardinality(key_cols) = 0 THEN
        RAISE EXCEPTION 'row-level localization requires a comparison key';
    END IF;

    SELECT format('%I.%I', n.nspname, c.relname)
    INTO rel_sql
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.oid = rel;

    IF rel_sql IS NULL THEN
        RAISE EXCEPTION 'relation % does not exist', rel;
    END IF;

    SELECT array_agg(a.attname ORDER BY a.attname)
    INTO selected_cols
    FROM unnest(cols) requested(col_name)
    JOIN pg_attribute a
      ON a.attrelid = rel
     AND a.attname = requested.col_name
     AND a.attnum > 0
     AND NOT a.attisdropped;

    IF selected_cols IS NULL OR cardinality(selected_cols) <> cardinality(cols) THEN
        RAISE EXCEPTION 'one or more requested columns are not present on %', rel::text;
    END IF;

    SELECT array_agg(a.attname ORDER BY ord.ordinality)
    INTO selected_key_cols
    FROM unnest(key_cols) WITH ORDINALITY AS ord(col_name, ordinality)
    JOIN pg_attribute a
      ON a.attrelid = rel
     AND a.attname = ord.col_name
     AND a.attnum > 0
     AND NOT a.attisdropped;

    IF selected_key_cols IS NULL OR cardinality(selected_key_cols) <> cardinality(key_cols) THEN
        RAISE EXCEPTION 'one or more key columns are not present on %', rel::text;
    END IF;

    SELECT
        array_agg(pgl_validate.column_encoding_mode(a.atttypid) ORDER BY a.attname),
        string_agg(format('t.%I', a.attname), ', ' ORDER BY a.attname)
    INTO enc_modes, digest_args
    FROM pg_attribute a
    WHERE a.attrelid = rel
      AND a.attname = ANY (selected_cols)
      AND a.attnum > 0
      AND NOT a.attisdropped;

    SELECT
        array_agg(pgl_validate.column_encoding_mode(a.atttypid) ORDER BY ord.ordinality),
        string_agg(format('t.%I', a.attname), ', ' ORDER BY ord.ordinality),
        string_agg(format('%L, t.%I', a.attname, a.attname), ', ' ORDER BY ord.ordinality),
        string_agg(format('t.%I', a.attname), ', ' ORDER BY ord.ordinality)
    INTO key_enc_modes, key_digest_args, key_text_args, order_args
    FROM unnest(selected_key_cols) WITH ORDINALITY AS ord(col_name, ordinality)
    JOIN pg_attribute a
      ON a.attrelid = rel
     AND a.attname = ord.col_name
     AND a.attnum > 0
     AND NOT a.attisdropped;

    RETURN format(
        'SELECT jsonb_build_object(%s)::text AS key_text, pgl_validate.row_digest(%L::int[], %s) AS key_bytes, pgl_validate.row_digest(%L::int[], %s) AS row_digest FROM %s t WHERE %s ORDER BY %s',
        key_text_args,
        key_enc_modes::text,
        key_digest_args,
        enc_modes::text,
        digest_args,
        rel_sql,
        CASE
            WHEN row_filter_sql IS NULL OR btrim(row_filter_sql) = '' THEN 'true'
            ELSE format('(%s)', row_filter_sql)
        END,
        order_args
    );
END
$$;

-- Generate the planner-visible SQL used to read a sequence last_value on each
-- participant. The returned SQL is safe to send to a peer with the same schema.
CREATE FUNCTION pgl_validate.plan_sequence_sql(seq regclass)
RETURNS text
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    seq_sql text;
BEGIN
    SELECT format('%I.%I', n.nspname, c.relname)
    INTO seq_sql
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.oid = seq
      AND c.relkind = 'S';

    IF seq_sql IS NULL THEN
        RAISE EXCEPTION 'relation % is not a sequence', seq;
    END IF;

    RETURN format('SELECT last_value::bigint AS last_value FROM %s', seq_sql);
END
$$;

-- First executable comparison path: compute and persist the local node's table
-- checksum using the same generated SQL that the coordinator will send to
-- remote peers. Multi-peer transport layers build on this catalog contract.
CREATE FUNCTION pgl_validate.compare_table(
    p_table_name regclass,
    peers text[] DEFAULT NULL,
    options jsonb DEFAULT '{}'
)
RETURNS pgl_validate.table_result
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
    v_run_id bigint;
    v_schema_name text;
    v_rel_name text;
    cols text[];
    key_cols text[];
    contract_repsets text[];
    contract_subscription name;
    contract_rec record;
    plan_repsets text[];
    repl_insert boolean := true;
    repl_update boolean := true;
    repl_delete boolean := true;
    repl_truncate boolean := true;
    has_row_filter boolean := false;
    row_filter_sql text;
    row_filter_exact boolean := true;
    sync_status "char" := 'r';
    validated_property text := 'full';
    exact_comparable boolean := true;
    contract_reason text := 'direct full-table comparison';
    pglogical_available boolean;
    table_in_pglogical boolean := false;
    requested_backend text;
    provider_dsn text;
    provider_node text;
    fence_timeout_ms int;
    fence_poll_interval_ms int;
    edge_seq int := 0;
    subscription_rec record;
    fence_rec pgl_validate.fence_attempt;
    peer_names text[];
    missing_peers text[];
    peer_rec record;
    remote_rec record;
    checksum_sql text;
    remote_checksum_sql text;
    localize_sql text;
    remote_localize_sql text;
    n_rows bigint;
    lthash bytea;
    differ_count int := 0;
    confirmed_count int := 0;
    advisory_count int := 0;
    indeterminate_count int := 0;
    participant_count int := 1;
    verdict text;
    result_reason text;
    result_row pgl_validate.table_result;
BEGIN
    SELECT n.nspname, c.relname
    INTO v_schema_name, v_rel_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.oid = p_table_name;

    IF v_schema_name IS NULL THEN
        RAISE EXCEPTION 'relation % does not exist', p_table_name;
    END IF;

    SELECT array_agg(a.attname ORDER BY a.attname)
    INTO cols
    FROM pg_attribute a
    WHERE a.attrelid = p_table_name
      AND a.attnum > 0
      AND NOT a.attisdropped;

    SELECT array_agg(a.attname ORDER BY ord.ordinality)
    INTO key_cols
    FROM pg_index i
    CROSS JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS ord(attnum, ordinality)
    JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ord.attnum
    WHERE i.indrelid = p_table_name
      AND i.indisprimary;

    requested_backend := COALESCE(NULLIF(options->>'backend', ''), 'pglogical');
    provider_dsn := NULLIF(options->>'provider_dsn', '');
    provider_node := COALESCE(NULLIF(options->>'provider_node', ''), 'local');
    fence_timeout_ms := COALESCE((NULLIF(options->>'fence_timeout_ms', ''))::int, 300000);
    fence_poll_interval_ms := COALESCE((NULLIF(options->>'fence_poll_interval_ms', ''))::int, 100);
    contract_subscription := NULLIF(options->>'subscription', '')::name;
    pglogical_available := to_regprocedure('pglogical.show_repset_table_info(regclass,text[])') IS NOT NULL;

    IF fence_timeout_ms <= 0 THEN
        RAISE EXCEPTION 'fence_timeout_ms must be greater than zero';
    END IF;
    IF fence_poll_interval_ms <= 0 THEN
        RAISE EXCEPTION 'fence_poll_interval_ms must be greater than zero';
    END IF;

    IF peers IS NULL OR cardinality(peers) = 0 THEN
        SELECT COALESCE(array_agg(p.name ORDER BY p.name), ARRAY[]::text[])
        INTO peer_names
        FROM pgl_validate.peer p;
    ELSE
        SELECT array_agg(DISTINCT requested.peer_name ORDER BY requested.peer_name)
        INTO peer_names
        FROM unnest(peers) AS requested(peer_name);

        SELECT array_agg(requested.peer_name ORDER BY requested.peer_name)
        INTO missing_peers
        FROM unnest(peer_names) AS requested(peer_name)
        LEFT JOIN pgl_validate.peer p ON p.name = requested.peer_name
        WHERE p.name IS NULL;

        IF missing_peers IS NOT NULL THEN
            RAISE EXCEPTION 'unknown pgl_validate peer(s): %', array_to_string(missing_peers, ', ');
        END IF;
    END IF;

    IF options ? 'repsets' THEN
        SELECT array_agg(DISTINCT elem.value ORDER BY elem.value)
        INTO contract_repsets
        FROM jsonb_array_elements_text(options->'repsets') AS elem(value);
    END IF;

    IF contract_repsets IS NULL OR cardinality(contract_repsets) = 0 THEN
        SELECT array_agg(DISTINCT peer_repset.repset ORDER BY peer_repset.repset)
        INTO contract_repsets
        FROM pgl_validate.peer p
        CROSS JOIN LATERAL unnest(p.replication_sets) AS peer_repset(repset)
        WHERE p.name = ANY (peer_names);
    END IF;

    IF pglogical_available THEN
        SELECT EXISTS (
            SELECT 1
            FROM pglogical.replication_set_table rst
            WHERE rst.set_reloid = p_table_name
        )
        INTO table_in_pglogical;
    ELSIF options ? 'backend' AND requested_backend = 'pglogical' THEN
        RAISE EXCEPTION 'backend=pglogical requested but pglogical is not installed in this database'
            USING ERRCODE = '0A000';
    END IF;

    IF requested_backend = 'pglogical'
       AND pglogical_available
       AND (table_in_pglogical
            OR contract_repsets IS NOT NULL
            OR contract_subscription IS NOT NULL) THEN
        SELECT *
        INTO contract_rec
        FROM pgl_validate.pglogical_table_contract(
            p_table_name,
            contract_repsets,
            contract_subscription
        );

        cols := contract_rec.att_list;
        key_cols := contract_rec.key_cols;
        plan_repsets := contract_rec.repsets;
        repl_insert := contract_rec.repl_insert;
        repl_update := contract_rec.repl_update;
        repl_delete := contract_rec.repl_delete;
        repl_truncate := contract_rec.repl_truncate;
        has_row_filter := contract_rec.has_row_filter;
        row_filter_sql := contract_rec.row_filter_sql;
        row_filter_exact := contract_rec.row_filter_exact;
        sync_status := contract_rec.sync_status;
        validated_property := contract_rec.validated_property;
        exact_comparable := contract_rec.exact_comparable;
        contract_reason := contract_rec.reason;
    END IF;

    INSERT INTO pgl_validate.run(status, options, tables_total)
    VALUES ('running', options, 1)
    RETURNING pgl_validate.run.run_id INTO v_run_id;

    INSERT INTO pgl_validate.run_participant(run_id, node, role, backend, pg_version, status)
    VALUES (v_run_id, 'local', 'coordinator', 'pglogical', current_setting('server_version_num')::int, 'connected');

    INSERT INTO pgl_validate.table_plan(
        run_id, schema_name, table_name, key_cols, att_list, repsets,
        repl_insert, repl_update, repl_delete, repl_truncate,
        has_row_filter, sync_status, validated_property
    )
    VALUES (
        v_run_id, v_schema_name, v_rel_name, key_cols, cols, plan_repsets,
        repl_insert, repl_update, repl_delete, repl_truncate,
        has_row_filter, sync_status, validated_property
    );

    IF NOT exact_comparable THEN
        IF has_row_filter AND NOT row_filter_exact THEN
            INSERT INTO pgl_validate.schema_issue(
                run_id, node, schema_name, table_name, issue_code, detail
            )
            VALUES (
                v_run_id,
                provider_node,
                v_schema_name,
                v_rel_name,
                'NONDETERMINISTIC_ROW_FILTER',
                contract_reason
            )
            ON CONFLICT DO NOTHING;
        END IF;

        verdict := CASE
            WHEN validated_property IN ('skipped','unsupported_mask') THEN 'skipped'
            ELSE 'partial'
        END;
        result_reason := format(
            'pglogical contract %s is not yet exact-comparable by the checksum-only path: %s',
            validated_property,
            contract_reason
        );

        INSERT INTO pgl_validate.table_result(
            run_id, schema_name, table_name, verdict, reason, finished_at
        )
        VALUES (
            v_run_id, v_schema_name, v_rel_name, verdict, result_reason, now()
        )
        RETURNING * INTO result_row;

        UPDATE pgl_validate.run
        SET status = 'completed',
            finished_at = now(),
            tables_matched = 0,
            tables_differ = 0
        WHERE pgl_validate.run.run_id = v_run_id;

        UPDATE pgl_validate.run_participant
        SET status = 'done'
        WHERE pgl_validate.run_participant.run_id = v_run_id
          AND node = 'local';

        RETURN result_row;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pgl_validate.peer p
        WHERE p.name = ANY (peer_names)
          AND p.backend = 'pglogical'
    ) THEN
        IF provider_dsn IS NULL THEN
            RAISE EXCEPTION
                'options.provider_dsn is required when comparing pglogical peers'
                USING ERRCODE = '0A000';
        END IF;

        INSERT INTO pgl_validate.fence_epoch(run_id, epoch_seq)
        VALUES (v_run_id, 1);

        UPDATE pgl_validate.run
        SET status = 'fencing'
        WHERE pgl_validate.run.run_id = v_run_id;

        FOR peer_rec IN
            SELECT p.name, p.dsn, p.backend, p.subscription_name,
                   p.connect_timeout_seconds,
                   p.statement_timeout_ms,
                   p.lock_timeout_ms
            FROM pgl_validate.peer p
            WHERE p.name = ANY (peer_names)
              AND p.backend = 'pglogical'
            ORDER BY p.name
        LOOP
            IF peer_rec.subscription_name IS NULL THEN
                RAISE EXCEPTION
                    'pglogical peer % requires subscription_name for exact barrier fencing',
                    peer_rec.name
                    USING ERRCODE = '0A000';
            END IF;

            SELECT *
            INTO subscription_rec
            FROM pgl_validate.remote_pglogical_subscription_status(
                peer_rec.dsn,
                peer_rec.subscription_name::text,
                peer_rec.connect_timeout_seconds,
                peer_rec.statement_timeout_ms,
                peer_rec.lock_timeout_ms
            );

            IF subscription_rec.status <> 'replicating' THEN
                RAISE EXCEPTION
                    'pglogical peer % subscription % is %, not replicating',
                    peer_rec.name,
                    peer_rec.subscription_name,
                    subscription_rec.status
                    USING ERRCODE = '57014';
            END IF;

            IF NOT (subscription_rec.replication_sets_json::jsonb ? 'pgl_validate_barrier') THEN
                RAISE EXCEPTION
                    'pglogical peer % subscription % does not include pgl_validate_barrier',
                    peer_rec.name,
                    peer_rec.subscription_name
                    USING ERRCODE = '0A000';
            END IF;

            edge_seq := edge_seq + 1;
            SELECT *
            INTO fence_rec
            FROM pgl_validate.fence_pglogical_edge(
                v_run_id,
                1,
                edge_seq,
                provider_node,
                peer_rec.name,
                provider_dsn,
                peer_rec.dsn,
                peer_rec.subscription_name::text,
                subscription_rec.slot_name,
                subscription_rec.slot_name,
                ARRAY['pgl_validate_barrier'],
                peer_rec.connect_timeout_seconds,
                peer_rec.statement_timeout_ms,
                peer_rec.lock_timeout_ms,
                fence_timeout_ms,
                fence_poll_interval_ms
            );

            IF fence_rec.status <> 'converged' THEN
                RAISE EXCEPTION
                    'pglogical peer % failed to converge barrier fence: %',
                    peer_rec.name,
                    fence_rec.status
                    USING ERRCODE = '57014';
            END IF;
        END LOOP;

        UPDATE pgl_validate.run_participant
        SET status = 'converged'
        WHERE pgl_validate.run_participant.run_id = v_run_id
          AND node = 'local';
    END IF;

    UPDATE pgl_validate.run
    SET status = 'running'
    WHERE pgl_validate.run.run_id = v_run_id;

    checksum_sql := pgl_validate.plan_chunk_sql(
        p_table_name,
        key_cols,
        NULL,
        NULL,
        cols,
        NULL,
        CASE WHEN validated_property = 'filtered_intersection' THEN row_filter_sql ELSE NULL END
    );
    remote_checksum_sql := pgl_validate.plan_chunk_sql(
        p_table_name,
        key_cols,
        NULL,
        NULL,
        cols,
        NULL,
        NULL
    );
    EXECUTE checksum_sql INTO n_rows, lthash;

    INSERT INTO pgl_validate.table_node_result(
        run_id, schema_name, table_name, node, n_rows, lthash, set_hash
    )
    VALUES (v_run_id, v_schema_name, v_rel_name, 'local', n_rows, lthash, NULL);

    FOR peer_rec IN
        SELECT p.name, p.dsn, p.backend,
               p.connect_timeout_seconds,
               p.statement_timeout_ms,
               p.lock_timeout_ms
        FROM pgl_validate.peer p
        WHERE p.name = ANY (peer_names)
        ORDER BY p.name
    LOOP
        SELECT rc.pg_version, rc.n_rows, rc.lthash
        INTO remote_rec
        FROM pgl_validate.remote_checksum(
            peer_rec.dsn,
            remote_checksum_sql,
            peer_rec.connect_timeout_seconds,
            peer_rec.statement_timeout_ms,
            peer_rec.lock_timeout_ms
        ) AS rc;

        participant_count := participant_count + 1;

        INSERT INTO pgl_validate.run_participant(
            run_id, node, role, backend, pg_version, dsn_ref, status
        )
        VALUES (
            v_run_id, peer_rec.name, 'participant', peer_rec.backend,
            remote_rec.pg_version, peer_rec.name, 'done'
        );

        INSERT INTO pgl_validate.table_node_result(
            run_id, schema_name, table_name, node, n_rows, lthash, set_hash
        )
        VALUES (
            v_run_id, v_schema_name, v_rel_name, peer_rec.name,
            remote_rec.n_rows, remote_rec.lthash, NULL
        );

        IF remote_rec.n_rows IS DISTINCT FROM n_rows
           OR remote_rec.lthash IS DISTINCT FROM lthash THEN
            differ_count := differ_count + 1;
        END IF;
    END LOOP;

    IF differ_count > 0
       AND key_cols IS NOT NULL
       AND cardinality(key_cols) > 0 THEN
        INSERT INTO pgl_validate.fence_epoch(run_id, epoch_seq)
        VALUES (v_run_id, 1)
        ON CONFLICT DO NOTHING;

        localize_sql := pgl_validate.plan_localize_sql(
            p_table_name,
            key_cols,
            cols,
            CASE WHEN validated_property = 'filtered_intersection' THEN row_filter_sql ELSE NULL END
        );
        remote_localize_sql := pgl_validate.plan_localize_sql(
            p_table_name,
            key_cols,
            cols,
            NULL
        );

        IF to_regclass('pg_temp.pgl_validate_localized_sample') IS NOT NULL THEN
            DROP TABLE pg_temp.pgl_validate_localized_sample;
        END IF;
        CREATE TEMP TABLE pgl_validate_localized_sample (
            sample     text NOT NULL,
            node       text NOT NULL,
            key_text   text NOT NULL,
            key_bytes  bytea NOT NULL,
            row_digest bytea NOT NULL
        ) ON COMMIT DROP;

        EXECUTE format(
            'INSERT INTO pg_temp.pgl_validate_localized_sample(sample, node, key_text, key_bytes, row_digest)
             SELECT %L, %L, q.key_text, q.key_bytes, q.row_digest FROM (%s) AS q',
            'A',
            'local',
            localize_sql
        );

        FOR peer_rec IN
            SELECT p.name, p.dsn, p.backend,
                   p.connect_timeout_seconds,
                   p.statement_timeout_ms,
                   p.lock_timeout_ms
            FROM pgl_validate.peer p
            WHERE p.name = ANY (peer_names)
            ORDER BY p.name
        LOOP
            INSERT INTO pg_temp.pgl_validate_localized_sample(
                sample, node, key_text, key_bytes, row_digest
            )
            SELECT 'A', peer_rec.name, r.key_text, r.key_bytes, r.row_digest
            FROM pgl_validate.remote_localize_rows(
                peer_rec.dsn,
                remote_localize_sql,
                peer_rec.connect_timeout_seconds,
                peer_rec.statement_timeout_ms,
                peer_rec.lock_timeout_ms
            ) AS r;

            INSERT INTO pgl_validate.divergence(
                run_id, schema_name, table_name, key_text, key_bytes,
                classification, node, status, detected_epoch, tuple
            )
            SELECT
                v_run_id,
                v_schema_name,
                v_rel_name,
                classified.key_text,
                classified.key_bytes,
                classified.classification,
                peer_rec.name,
                CASE
                    WHEN classified.classification IN ('missing_on','extra_on')
                     AND validated_property IN ('filtered_intersection','filtered_advisory')
                    THEN 'advisory'
                    WHEN classified.classification = 'extra_on'
                     AND validated_property = 'superset'
                    THEN 'advisory'
                    ELSE 'candidate'
                END,
                1,
                NULL
            FROM (
                SELECT
                    COALESCE(l.key_text, r.key_text) AS key_text,
                    COALESCE(l.key_bytes, r.key_bytes) AS key_bytes,
                    CASE
                        WHEN r.key_bytes IS NULL THEN 'missing_on'
                        WHEN l.key_bytes IS NULL THEN 'extra_on'
                        WHEN l.row_digest IS DISTINCT FROM r.row_digest
                         AND validated_property <> 'keys_only'
                        THEN 'differs'
                        ELSE NULL
                    END AS classification
                FROM (
                    SELECT key_text, key_bytes, row_digest
                    FROM pg_temp.pgl_validate_localized_sample
                    WHERE sample = 'A' AND node = 'local'
                ) l
                FULL OUTER JOIN (
                    SELECT key_text, key_bytes, row_digest
                    FROM pg_temp.pgl_validate_localized_sample
                    WHERE sample = 'A' AND node = peer_rec.name
                ) r USING (key_bytes)
            ) classified
            WHERE classified.classification IS NOT NULL
            ON CONFLICT (run_id, schema_name, table_name, key_bytes, node) DO UPDATE
            SET classification = EXCLUDED.classification,
                status = EXCLUDED.status,
                detected_epoch = EXCLUDED.detected_epoch,
                detected_at = now();
        END LOOP;

        IF EXISTS (
            SELECT 1
            FROM pgl_validate.divergence d
            JOIN pgl_validate.peer p ON p.name = d.node
            WHERE d.run_id = v_run_id
              AND d.schema_name = v_schema_name
              AND d.table_name = v_rel_name
              AND d.status = 'candidate'
              AND p.backend = 'pglogical'
        ) THEN
            INSERT INTO pgl_validate.fence_epoch(run_id, epoch_seq)
            VALUES (v_run_id, 2)
            ON CONFLICT DO NOTHING;

            UPDATE pgl_validate.run
            SET status = 'rechecking'
            WHERE pgl_validate.run.run_id = v_run_id;

            FOR peer_rec IN
                SELECT p.name, p.dsn, p.backend, p.subscription_name,
                       p.connect_timeout_seconds,
                       p.statement_timeout_ms,
                       p.lock_timeout_ms,
                       re.edge_id,
                       re.slot_name,
                       re.origin_name
                FROM pgl_validate.peer p
                JOIN pgl_validate.run_edge re
                  ON re.run_id = v_run_id
                 AND re.target_node = p.name
                WHERE p.name = ANY (peer_names)
                  AND p.backend = 'pglogical'
                ORDER BY p.name
            LOOP
                SELECT *
                INTO fence_rec
                FROM pgl_validate.fence_pglogical_edge(
                    v_run_id,
                    2,
                    peer_rec.edge_id,
                    provider_node,
                    peer_rec.name,
                    provider_dsn,
                    peer_rec.dsn,
                    peer_rec.subscription_name::text,
                    peer_rec.slot_name,
                    peer_rec.origin_name,
                    ARRAY['pgl_validate_barrier'],
                    peer_rec.connect_timeout_seconds,
                    peer_rec.statement_timeout_ms,
                    peer_rec.lock_timeout_ms,
                    fence_timeout_ms,
                    fence_poll_interval_ms
                );

                IF fence_rec.status <> 'converged' THEN
                    RAISE EXCEPTION
                        'pglogical peer % failed to converge recheck fence: %',
                        peer_rec.name,
                        fence_rec.status
                        USING ERRCODE = '57014';
                END IF;
            END LOOP;

            EXECUTE format(
                'INSERT INTO pg_temp.pgl_validate_localized_sample(sample, node, key_text, key_bytes, row_digest)
                 SELECT %L, %L, q.key_text, q.key_bytes, q.row_digest FROM (%s) AS q',
                'B',
                'local',
                localize_sql
            );

            FOR peer_rec IN
                SELECT p.name, p.dsn, p.backend,
                       p.connect_timeout_seconds,
                       p.statement_timeout_ms,
                       p.lock_timeout_ms
                FROM pgl_validate.peer p
                WHERE p.name = ANY (peer_names)
                  AND p.backend = 'pglogical'
                ORDER BY p.name
            LOOP
                INSERT INTO pg_temp.pgl_validate_localized_sample(
                    sample, node, key_text, key_bytes, row_digest
                )
                SELECT 'B', peer_rec.name, r.key_text, r.key_bytes, r.row_digest
                FROM pgl_validate.remote_localize_rows(
                    peer_rec.dsn,
                    remote_localize_sql,
                    peer_rec.connect_timeout_seconds,
                    peer_rec.statement_timeout_ms,
                    peer_rec.lock_timeout_ms
                ) AS r;

                INSERT INTO pgl_validate.divergence_recheck(
                    run_id, schema_name, table_name, key_bytes, node, epoch_seq, outcome
                )
                SELECT
                    d.run_id,
                    d.schema_name,
                    d.table_name,
                    d.key_bytes,
                    d.node,
                    2,
                    CASE
                        WHEN (lb.key_bytes IS NOT NULL AND pb.key_bytes IS NOT NULL
                              AND lb.row_digest IS NOT DISTINCT FROM pb.row_digest)
                          OR (lb.key_bytes IS NULL AND pb.key_bytes IS NULL)
                        THEN 'cleared'
                        WHEN la.row_digest IS NOT DISTINCT FROM lb.row_digest
                         AND pa.row_digest IS NOT DISTINCT FROM pb.row_digest
                        THEN 'still_differs'
                        ELSE 'still_hot'
                    END
                FROM pgl_validate.divergence d
                LEFT JOIN pg_temp.pgl_validate_localized_sample la
                  ON la.sample = 'A' AND la.node = 'local' AND la.key_bytes = d.key_bytes
                LEFT JOIN pg_temp.pgl_validate_localized_sample pa
                  ON pa.sample = 'A' AND pa.node = d.node AND pa.key_bytes = d.key_bytes
                LEFT JOIN pg_temp.pgl_validate_localized_sample lb
                  ON lb.sample = 'B' AND lb.node = 'local' AND lb.key_bytes = d.key_bytes
                LEFT JOIN pg_temp.pgl_validate_localized_sample pb
                  ON pb.sample = 'B' AND pb.node = d.node AND pb.key_bytes = d.key_bytes
                WHERE d.run_id = v_run_id
                  AND d.schema_name = v_schema_name
                  AND d.table_name = v_rel_name
                  AND d.node = peer_rec.name
                  AND d.status = 'candidate'
                ON CONFLICT (run_id, schema_name, table_name, key_bytes, node, epoch_seq)
                DO UPDATE SET outcome = EXCLUDED.outcome, at = now();

                UPDATE pgl_validate.divergence d
                SET status = CASE r.outcome
                    WHEN 'cleared' THEN 'cleared'
                    WHEN 'still_differs' THEN 'confirmed'
                    ELSE 'indeterminate'
                END
                FROM pgl_validate.divergence_recheck r
                WHERE r.run_id = d.run_id
                  AND r.schema_name = d.schema_name
                  AND r.table_name = d.table_name
                  AND r.key_bytes = d.key_bytes
                  AND r.node = d.node
                  AND r.epoch_seq = 2
                  AND d.run_id = v_run_id
                  AND d.schema_name = v_schema_name
                  AND d.table_name = v_rel_name
                  AND d.node = peer_rec.name
                  AND d.status = 'candidate';
            END LOOP;
        END IF;

        UPDATE pgl_validate.divergence d
        SET status = 'confirmed'
        FROM pgl_validate.peer p
        WHERE p.name = d.node
          AND p.backend <> 'pglogical'
          AND d.run_id = v_run_id
          AND d.schema_name = v_schema_name
          AND d.table_name = v_rel_name
          AND d.status = 'candidate';

        SELECT
            count(*) FILTER (WHERE status = 'confirmed'),
            count(*) FILTER (WHERE status = 'advisory'),
            count(*) FILTER (WHERE status = 'indeterminate')
        INTO confirmed_count, advisory_count, indeterminate_count
        FROM pgl_validate.divergence d
        WHERE d.run_id = v_run_id
          AND d.schema_name = v_schema_name
          AND d.table_name = v_rel_name;
    END IF;

    IF differ_count = 0 THEN
        verdict := 'match';
        IF participant_count = 1 THEN
            result_reason := format(
                'single local participant; no peers registered or requested; validated_property=%s',
                validated_property
            );
        ELSE
            result_reason := format(
                'all %s participants have matching row count and LtHash; validated_property=%s',
                participant_count,
                validated_property
            );
        END IF;
    ELSIF key_cols IS NULL OR cardinality(key_cols) = 0 THEN
        verdict := 'differ';
        result_reason := format(
            '%s of %s remote peer(s) differ from local; row-level localization unavailable without a key',
            differ_count,
            participant_count - 1
        );
    ELSIF confirmed_count > 0 THEN
        verdict := 'differ';
        result_reason := format(
            '%s confirmed divergence(s), %s advisory difference(s), %s indeterminate key(s); validated_property=%s',
            confirmed_count,
            advisory_count,
            indeterminate_count,
            validated_property
        );
    ELSIF indeterminate_count > 0 THEN
        verdict := 'indeterminate';
        result_reason := format(
            'checksum mismatch localized, but %s key(s) remained hot after recheck; %s advisory difference(s); validated_property=%s',
            indeterminate_count,
            advisory_count,
            validated_property
        );
    ELSE
        verdict := 'match';
        result_reason := format(
            'initial checksum mismatch produced no confirmed divergence after localization/recheck; advisory differences=%s; validated_property=%s',
            advisory_count,
            validated_property
        );
    END IF;

    INSERT INTO pgl_validate.table_result(
        run_id, schema_name, table_name, verdict, reason, finished_at
    )
    VALUES (
        v_run_id, v_schema_name, v_rel_name, verdict, result_reason, now()
    )
    RETURNING * INTO result_row;

    UPDATE pgl_validate.run
    SET status = 'completed',
        finished_at = now(),
        tables_matched = CASE WHEN differ_count = 0 THEN 1 ELSE 0 END,
        tables_differ = CASE WHEN differ_count = 0 THEN 0 ELSE 1 END
    WHERE pgl_validate.run.run_id = v_run_id;

    UPDATE pgl_validate.run_participant
    SET status = 'done'
    WHERE pgl_validate.run_participant.run_id = v_run_id
      AND node = 'local';

    RETURN result_row;
END
$$;

CREATE FUNCTION pgl_validate.compare_sequence(
    sequence_name regclass,
    peers text[] DEFAULT NULL,
    options jsonb DEFAULT '{}'
)
RETURNS SETOF pgl_validate.sequence_result
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
    v_run_id bigint;
    v_schema_name text;
    v_seq_name text;
    peer_names text[];
    missing_peers text[];
    peer_rec record;
    remote_seq_rec record;
    subscription_rec record;
    fence_rec pgl_validate.fence_attempt;
    provider_dsn text := NULLIF(options->>'provider_dsn', '');
    provider_node text := COALESCE(NULLIF(options->>'provider_node', ''), 'local');
    fence_timeout_ms int := COALESCE((NULLIF(options->>'fence_timeout_ms', ''))::int, 300000);
    fence_poll_interval_ms int := COALESCE((NULLIF(options->>'fence_poll_interval_ms', ''))::int, 100);
    buffer_multiplier int := COALESCE((NULLIF(options->>'sequence_buffer_multiplier', ''))::int, 2);
    edge_seq int := 0;
    sequence_sql text;
    provider_last_value bigint;
    subscriber_last_value bigint;
    cache_size int;
    window_max numeric;
    verdict text;
    within_contract boolean;
BEGIN
    SELECT n.nspname, c.relname
    INTO v_schema_name, v_seq_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.oid = sequence_name
      AND c.relkind = 'S';

    IF v_schema_name IS NULL THEN
        RAISE EXCEPTION 'relation % is not a sequence', sequence_name;
    END IF;
    IF fence_timeout_ms <= 0 THEN
        RAISE EXCEPTION 'fence_timeout_ms must be greater than zero';
    END IF;
    IF fence_poll_interval_ms <= 0 THEN
        RAISE EXCEPTION 'fence_poll_interval_ms must be greater than zero';
    END IF;
    IF buffer_multiplier <= 0 THEN
        RAISE EXCEPTION 'sequence_buffer_multiplier must be greater than zero';
    END IF;

    IF peers IS NULL OR cardinality(peers) = 0 THEN
        SELECT COALESCE(array_agg(p.name ORDER BY p.name), ARRAY[]::text[])
        INTO peer_names
        FROM pgl_validate.peer p;
    ELSE
        SELECT array_agg(DISTINCT requested.peer_name ORDER BY requested.peer_name)
        INTO peer_names
        FROM unnest(peers) AS requested(peer_name);

        SELECT array_agg(requested.peer_name ORDER BY requested.peer_name)
        INTO missing_peers
        FROM unnest(peer_names) AS requested(peer_name)
        LEFT JOIN pgl_validate.peer p ON p.name = requested.peer_name
        WHERE p.name IS NULL;

        IF missing_peers IS NOT NULL THEN
            RAISE EXCEPTION 'unknown pgl_validate peer(s): %', array_to_string(missing_peers, ', ');
        END IF;
    END IF;

    INSERT INTO pgl_validate.run(status, options, tables_total)
    VALUES ('running', options, 0)
    RETURNING pgl_validate.run.run_id INTO v_run_id;

    INSERT INTO pgl_validate.run_participant(run_id, node, role, backend, pg_version, status)
    VALUES (v_run_id, 'local', 'coordinator', 'pglogical', current_setting('server_version_num')::int, 'connected');

    IF EXISTS (
        SELECT 1
        FROM pgl_validate.peer p
        WHERE p.name = ANY (peer_names)
          AND p.backend = 'pglogical'
    ) THEN
        IF provider_dsn IS NULL THEN
            RAISE EXCEPTION
                'options.provider_dsn is required when comparing pglogical peers'
                USING ERRCODE = '0A000';
        END IF;

        INSERT INTO pgl_validate.fence_epoch(run_id, epoch_seq)
        VALUES (v_run_id, 1);

        UPDATE pgl_validate.run
        SET status = 'fencing'
        WHERE pgl_validate.run.run_id = v_run_id;

        FOR peer_rec IN
            SELECT p.name, p.dsn, p.backend, p.subscription_name,
                   p.connect_timeout_seconds,
                   p.statement_timeout_ms,
                   p.lock_timeout_ms
            FROM pgl_validate.peer p
            WHERE p.name = ANY (peer_names)
              AND p.backend = 'pglogical'
            ORDER BY p.name
        LOOP
            IF peer_rec.subscription_name IS NULL THEN
                RAISE EXCEPTION
                    'pglogical peer % requires subscription_name for exact barrier fencing',
                    peer_rec.name
                    USING ERRCODE = '0A000';
            END IF;

            SELECT *
            INTO subscription_rec
            FROM pgl_validate.remote_pglogical_subscription_status(
                peer_rec.dsn,
                peer_rec.subscription_name::text,
                peer_rec.connect_timeout_seconds,
                peer_rec.statement_timeout_ms,
                peer_rec.lock_timeout_ms
            );

            IF subscription_rec.status <> 'replicating' THEN
                RAISE EXCEPTION
                    'pglogical peer % subscription % is %, not replicating',
                    peer_rec.name,
                    peer_rec.subscription_name,
                    subscription_rec.status
                    USING ERRCODE = '57014';
            END IF;

            IF NOT (subscription_rec.replication_sets_json::jsonb ? 'pgl_validate_barrier') THEN
                RAISE EXCEPTION
                    'pglogical peer % subscription % does not include pgl_validate_barrier',
                    peer_rec.name,
                    peer_rec.subscription_name
                    USING ERRCODE = '0A000';
            END IF;

            edge_seq := edge_seq + 1;
            SELECT *
            INTO fence_rec
            FROM pgl_validate.fence_pglogical_edge(
                v_run_id,
                1,
                edge_seq,
                provider_node,
                peer_rec.name,
                provider_dsn,
                peer_rec.dsn,
                peer_rec.subscription_name::text,
                subscription_rec.slot_name,
                subscription_rec.slot_name,
                ARRAY['pgl_validate_barrier'],
                peer_rec.connect_timeout_seconds,
                peer_rec.statement_timeout_ms,
                peer_rec.lock_timeout_ms,
                fence_timeout_ms,
                fence_poll_interval_ms
            );

            IF fence_rec.status <> 'converged' THEN
                RAISE EXCEPTION
                    'pglogical peer % failed to converge barrier fence: %',
                    peer_rec.name,
                    fence_rec.status
                    USING ERRCODE = '57014';
            END IF;
        END LOOP;
    END IF;

    UPDATE pgl_validate.run
    SET status = 'running'
    WHERE pgl_validate.run.run_id = v_run_id;

    sequence_sql := pgl_validate.plan_sequence_sql(sequence_name);
    EXECUTE sequence_sql INTO provider_last_value;

    IF to_regclass('pglogical.sequence_state') IS NOT NULL THEN
        SELECT COALESCE(ss.cache_size, ps.cache_size, 1)::int
        INTO cache_size
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        LEFT JOIN pglogical.sequence_state ss ON ss.seqoid = c.oid
        LEFT JOIN pg_sequences ps
          ON ps.schemaname = n.nspname
         AND ps.sequencename = c.relname
        WHERE c.oid = sequence_name;
    ELSE
        SELECT COALESCE(ps.cache_size, 1)::int
        INTO cache_size
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        LEFT JOIN pg_sequences ps
          ON ps.schemaname = n.nspname
         AND ps.sequencename = c.relname
        WHERE c.oid = sequence_name;
    END IF;

    cache_size := GREATEST(COALESCE(cache_size, 1), 1);
    window_max := provider_last_value::numeric + (buffer_multiplier::numeric * cache_size::numeric);

    FOR peer_rec IN
        SELECT p.name, p.dsn, p.backend,
               p.connect_timeout_seconds,
               p.statement_timeout_ms,
               p.lock_timeout_ms
        FROM pgl_validate.peer p
        WHERE p.name = ANY (peer_names)
        ORDER BY p.name
    LOOP
        remote_seq_rec := NULL;
        subscriber_last_value := NULL;

        BEGIN
            SELECT r.pg_version, r.last_value
            INTO remote_seq_rec
            FROM pgl_validate.remote_sequence_value(
                peer_rec.dsn,
                sequence_sql,
                peer_rec.connect_timeout_seconds,
                peer_rec.statement_timeout_ms,
                peer_rec.lock_timeout_ms
            ) AS r;

            subscriber_last_value := remote_seq_rec.last_value;

            IF subscriber_last_value < provider_last_value THEN
                verdict := 'behind';
                within_contract := false;
            ELSIF subscriber_last_value::numeric > window_max THEN
                verdict := 'ahead_of_window';
                within_contract := false;
            ELSE
                verdict := 'match';
                within_contract := true;
            END IF;
        EXCEPTION WHEN others THEN
            subscriber_last_value := NULL;
            verdict := 'error';
            within_contract := false;
        END;

        INSERT INTO pgl_validate.run_participant(
            run_id, node, role, backend, pg_version, dsn_ref, status
        )
        VALUES (
            v_run_id, peer_rec.name, 'participant', peer_rec.backend,
            COALESCE(remote_seq_rec.pg_version, current_setting('server_version_num')::int),
            peer_rec.name, 'done'
        )
        ON CONFLICT (run_id, node) DO NOTHING;

        INSERT INTO pgl_validate.sequence_result(
            run_id, schema_name, seq_name, provider_node, provider_last_value,
            subscriber_node, subscriber_last_value, cache_size, within_contract, verdict
        )
        VALUES (
            v_run_id, v_schema_name, v_seq_name, provider_node, provider_last_value,
            peer_rec.name, subscriber_last_value, cache_size, within_contract, verdict
        );
    END LOOP;

    UPDATE pgl_validate.run
    SET status = 'completed',
        finished_at = now()
    WHERE pgl_validate.run.run_id = v_run_id;

    UPDATE pgl_validate.run_participant
    SET status = 'done'
    WHERE pgl_validate.run_participant.run_id = v_run_id
      AND node = 'local';

    RETURN QUERY
    SELECT sr.*
    FROM pgl_validate.sequence_result sr
    WHERE sr.run_id = v_run_id
    ORDER BY sr.schema_name, sr.seq_name, sr.subscriber_node;
END
$$;

CREATE FUNCTION pgl_validate.run_status(run_id bigint)
RETURNS pgl_validate.run
LANGUAGE sql
STABLE
AS $$
    SELECT r FROM pgl_validate.run r WHERE r.run_id = run_status.run_id
$$;

CREATE FUNCTION pgl_validate.divergences(run_id bigint)
RETURNS SETOF pgl_validate.divergence
LANGUAGE sql
STABLE
AS $$
    SELECT d.* FROM pgl_validate.divergence d WHERE d.run_id = divergences.run_id
$$;

CREATE FUNCTION pgl_validate.sequences(run_id bigint)
RETURNS SETOF pgl_validate.sequence_result
LANGUAGE sql
STABLE
AS $$
    SELECT s.* FROM pgl_validate.sequence_result s WHERE s.run_id = sequences.run_id
$$;

CREATE FUNCTION pgl_validate.report(p_run_id bigint)
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
WITH selected_run AS (
    SELECT r.*
    FROM pgl_validate.run r
    WHERE r.run_id = p_run_id
)
SELECT CASE
    WHEN NOT EXISTS (SELECT 1 FROM selected_run) THEN
        jsonb_build_object('run_id', p_run_id, 'error', 'run not found')
    ELSE
        jsonb_build_object(
            'run', (SELECT to_jsonb(r) FROM selected_run r),
            'participants',
                COALESCE((
                    SELECT jsonb_agg(to_jsonb(rp) ORDER BY rp.node)
                    FROM pgl_validate.run_participant rp
                    WHERE rp.run_id = p_run_id
                ), '[]'::jsonb),
            'tables',
                COALESCE((
                    SELECT jsonb_agg(
                        jsonb_build_object(
                            'plan', to_jsonb(tp),
                            'result', to_jsonb(tr),
                            'nodes',
                                COALESCE((
                                    SELECT jsonb_agg(to_jsonb(tnr) ORDER BY tnr.node)
                                    FROM pgl_validate.table_node_result tnr
                                    WHERE tnr.run_id = tp.run_id
                                      AND tnr.schema_name = tp.schema_name
                                      AND tnr.table_name = tp.table_name
                                ), '[]'::jsonb),
                            'chunks',
                                COALESCE((
                                    SELECT jsonb_agg(
                                        jsonb_build_object(
                                            'chunk', to_jsonb(cr),
                                            'nodes',
                                                COALESCE((
                                                    SELECT jsonb_agg(to_jsonb(cnr) ORDER BY cnr.node)
                                                    FROM pgl_validate.chunk_node_result cnr
                                                    WHERE cnr.run_id = cr.run_id
                                                      AND cnr.schema_name = cr.schema_name
                                                      AND cnr.table_name = cr.table_name
                                                      AND cnr.chunk_id = cr.chunk_id
                                                ), '[]'::jsonb)
                                        )
                                        ORDER BY cr.chunk_id
                                    )
                                    FROM pgl_validate.chunk_result cr
                                    WHERE cr.run_id = tp.run_id
                                      AND cr.schema_name = tp.schema_name
                                      AND cr.table_name = tp.table_name
                                ), '[]'::jsonb),
                            'divergences',
                                COALESCE((
                                    SELECT jsonb_agg(
                                        jsonb_build_object(
                                            'divergence', to_jsonb(d),
                                            'rechecks',
                                                COALESCE((
                                                    SELECT jsonb_agg(to_jsonb(dr) ORDER BY dr.epoch_seq)
                                                    FROM pgl_validate.divergence_recheck dr
                                                    WHERE dr.run_id = d.run_id
                                                      AND dr.schema_name = d.schema_name
                                                      AND dr.table_name = d.table_name
                                                      AND dr.key_bytes = d.key_bytes
                                                      AND dr.node = d.node
                                                ), '[]'::jsonb)
                                        )
                                        ORDER BY d.detected_at, d.node, d.key_text
                                    )
                                    FROM pgl_validate.divergence d
                                    WHERE d.run_id = tp.run_id
                                      AND d.schema_name = tp.schema_name
                                      AND d.table_name = tp.table_name
                                ), '[]'::jsonb)
                        )
                        ORDER BY tp.schema_name, tp.table_name
                    )
                    FROM pgl_validate.table_plan tp
                    LEFT JOIN pgl_validate.table_result tr
                      ON tr.run_id = tp.run_id
                     AND tr.schema_name = tp.schema_name
                     AND tr.table_name = tp.table_name
                    WHERE tp.run_id = p_run_id
                ), '[]'::jsonb),
            'sequences',
                COALESCE((
                    SELECT jsonb_agg(to_jsonb(sr) ORDER BY sr.schema_name, sr.seq_name, sr.subscriber_node)
                    FROM pgl_validate.sequence_result sr
                    WHERE sr.run_id = p_run_id
                ), '[]'::jsonb),
            'schema_issues',
                COALESCE((
                    SELECT jsonb_agg(to_jsonb(si) ORDER BY si.node, si.schema_name, si.table_name, si.issue_code)
                    FROM pgl_validate.schema_issue si
                    WHERE si.run_id = p_run_id
                ), '[]'::jsonb),
            'fence',
                jsonb_build_object(
                    'epochs',
                        COALESCE((
                            SELECT jsonb_agg(to_jsonb(fe) ORDER BY fe.epoch_seq)
                            FROM pgl_validate.fence_epoch fe
                            WHERE fe.run_id = p_run_id
                        ), '[]'::jsonb),
                    'edges',
                        COALESCE((
                            SELECT jsonb_agg(to_jsonb(re) ORDER BY re.edge_id)
                            FROM pgl_validate.run_edge re
                            WHERE re.run_id = p_run_id
                        ), '[]'::jsonb),
                    'targets',
                        COALESCE((
                            SELECT jsonb_agg(to_jsonb(fedge) ORDER BY fedge.epoch_seq, fedge.edge_id)
                            FROM pgl_validate.fence_edge fedge
                            WHERE fedge.run_id = p_run_id
                        ), '[]'::jsonb),
                    'attempts',
                        COALESCE((
                            SELECT jsonb_agg(to_jsonb(fa) ORDER BY fa.epoch_seq, fa.edge_id)
                            FROM pgl_validate.fence_attempt fa
                            WHERE fa.run_id = p_run_id
                        ), '[]'::jsonb),
                    'barriers',
                        COALESCE((
                            SELECT jsonb_agg(to_jsonb(fbr) ORDER BY fbr.epoch_seq, fbr.edge_id)
                            FROM pgl_validate.fence_barrier_run fbr
                            WHERE fbr.run_id = p_run_id
                        ), '[]'::jsonb)
                )
        )
END
$$;

CREATE FUNCTION pgl_validate.metrics()
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
SELECT jsonb_build_object(
    'runs',
        jsonb_build_object(
            'total', (SELECT count(*) FROM pgl_validate.run),
            'by_status',
                COALESCE((
                    SELECT jsonb_object_agg(status, n)
                    FROM (
                        SELECT r.status, count(*) AS n
                        FROM pgl_validate.run r
                        GROUP BY r.status
                        ORDER BY r.status
                    ) s
                ), '{}'::jsonb),
            'last_completed_at',
                (SELECT max(r.finished_at) FROM pgl_validate.run r WHERE r.status = 'completed')
        ),
    'tables',
        jsonb_build_object(
            'by_verdict',
                COALESCE((
                    SELECT jsonb_object_agg(verdict, n)
                    FROM (
                        SELECT tr.verdict, count(*) AS n
                        FROM pgl_validate.table_result tr
                        GROUP BY tr.verdict
                        ORDER BY tr.verdict
                    ) s
                ), '{}'::jsonb),
            'last_successful_validation',
                (SELECT max(tr.finished_at) FROM pgl_validate.table_result tr WHERE tr.verdict = 'match')
        ),
    'sequences',
        jsonb_build_object(
            'by_verdict',
                COALESCE((
                    SELECT jsonb_object_agg(verdict, n)
                    FROM (
                        SELECT sr.verdict, count(*) AS n
                        FROM pgl_validate.sequence_result sr
                        GROUP BY sr.verdict
                        ORDER BY sr.verdict
                    ) s
                ), '{}'::jsonb),
            'out_of_contract',
                (SELECT count(*) FROM pgl_validate.sequence_result sr WHERE NOT sr.within_contract)
        ),
    'divergences',
        jsonb_build_object(
            'by_status',
                COALESCE((
                    SELECT jsonb_object_agg(status, n)
                    FROM (
                        SELECT d.status, count(*) AS n
                        FROM pgl_validate.divergence d
                        GROUP BY d.status
                        ORDER BY d.status
                    ) s
                ), '{}'::jsonb),
            'confirmed',
                (SELECT count(*) FROM pgl_validate.divergence d WHERE d.status = 'confirmed')
        ),
    'fences',
        jsonb_build_object(
            'attempts_by_status',
                COALESCE((
                    SELECT jsonb_object_agg(status, n)
                    FROM (
                        SELECT fa.status, count(*) AS n
                        FROM pgl_validate.fence_attempt fa
                        GROUP BY fa.status
                        ORDER BY fa.status
                    ) s
                ), '{}'::jsonb)
        )
)
$$;

CREATE FUNCTION pgl_validate.record_barrier_fence(
    p_run_id bigint,
    p_epoch_seq int,
    p_edge_id int,
    p_token uuid,
    p_origin_node text,
    p_barrier_end_lsn pg_lsn
)
RETURNS void
LANGUAGE plpgsql
VOLATILE
AS $$
BEGIN
    IF p_token IS NULL THEN
        RAISE EXCEPTION 'barrier token is required';
    END IF;
    IF p_barrier_end_lsn IS NULL THEN
        RAISE EXCEPTION 'barrier_end_lsn is required';
    END IF;

    INSERT INTO pgl_validate.fence_epoch(run_id, epoch_seq)
    VALUES (p_run_id, p_epoch_seq)
    ON CONFLICT (run_id, epoch_seq) DO NOTHING;

    INSERT INTO pgl_validate.fence_edge(
        run_id, epoch_seq, edge_id, fence_kind, barrier_token, barrier_end_lsn
    )
    VALUES (
        p_run_id,
        p_epoch_seq,
        p_edge_id,
        'barrier',
        p_token,
        p_barrier_end_lsn
    )
    ON CONFLICT (run_id, epoch_seq, edge_id) DO UPDATE
    SET fence_kind = 'barrier',
        barrier_token = EXCLUDED.barrier_token,
        barrier_end_lsn = EXCLUDED.barrier_end_lsn;

    INSERT INTO pgl_validate.fence_barrier_run(
        token, run_id, epoch_seq, edge_id, origin_node, barrier_end_lsn
    )
    VALUES (
        p_token,
        p_run_id,
        p_epoch_seq,
        p_edge_id,
        p_origin_node,
        p_barrier_end_lsn
    )
    ON CONFLICT (run_id, epoch_seq, edge_id) DO UPDATE
    SET token = EXCLUDED.token,
        origin_node = EXCLUDED.origin_node,
        barrier_end_lsn = EXCLUDED.barrier_end_lsn;
END
$$;

CREATE FUNCTION pgl_validate.record_fence_attempt(
    p_run_id bigint,
    p_epoch_seq int,
    p_edge_id int,
    p_barrier_end_lsn pg_lsn,
    p_origin_progress_lsn pg_lsn,
    p_token_visible boolean,
    p_confirmed_flush_lsn pg_lsn DEFAULT NULL,
    p_status text DEFAULT NULL
)
RETURNS pgl_validate.fence_attempt
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
    derived_status text;
    result_row pgl_validate.fence_attempt;
BEGIN
    IF p_barrier_end_lsn IS NULL THEN
        RAISE EXCEPTION 'barrier_end_lsn is required';
    END IF;
    IF p_token_visible IS NULL THEN
        RAISE EXCEPTION 'token_visible is required';
    END IF;

    derived_status := COALESCE(
        p_status,
        CASE
            WHEN p_origin_progress_lsn IS NOT NULL
             AND p_origin_progress_lsn >= p_barrier_end_lsn
             AND p_token_visible
            THEN 'converged'
            ELSE 'waiting'
        END
    );

    IF derived_status NOT IN ('waiting','converged','timeout','degraded') THEN
        RAISE EXCEPTION 'invalid fence attempt status: %', derived_status;
    END IF;

    INSERT INTO pgl_validate.fence_attempt(
        run_id, epoch_seq, edge_id, barrier_end_lsn, origin_progress_lsn,
        token_visible, confirmed_flush_lsn, converged_at, status
    )
    VALUES (
        p_run_id, p_epoch_seq, p_edge_id, p_barrier_end_lsn, p_origin_progress_lsn,
        p_token_visible, p_confirmed_flush_lsn,
        CASE WHEN derived_status = 'converged' THEN now() ELSE NULL END,
        derived_status
    )
    ON CONFLICT (run_id, epoch_seq, edge_id) DO UPDATE
    SET barrier_end_lsn = EXCLUDED.barrier_end_lsn,
        origin_progress_lsn = EXCLUDED.origin_progress_lsn,
        token_visible = EXCLUDED.token_visible,
        confirmed_flush_lsn = EXCLUDED.confirmed_flush_lsn,
        converged_at = EXCLUDED.converged_at,
        status = EXCLUDED.status
    RETURNING * INTO result_row;

    RETURN result_row;
END
$$;

CREATE FUNCTION pgl_validate.protected_barrier_tokens()
RETURNS uuid[]
LANGUAGE sql
STABLE
AS $$
    SELECT COALESCE(array_agg(br.token), ARRAY[]::uuid[])
    FROM pgl_validate.fence_barrier_run br
    JOIN pgl_validate.run r USING (run_id)
    WHERE r.status NOT IN ('completed','failed','canceled')
$$;

CREATE FUNCTION pgl_validate.cleanup_fence_barriers(
    barrier_retention interval DEFAULT interval '1 hour',
    protected uuid[] DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
    protected_tokens uuid[] := COALESCE(protected, pgl_validate.protected_barrier_tokens());
    deleted_count bigint;
BEGIN
    WITH deleted AS (
        DELETE FROM pgl_validate.fence_barrier
        WHERE injected_at < now() - barrier_retention
          AND NOT (token = ANY (protected_tokens))
        RETURNING 1
    )
    SELECT count(*) INTO deleted_count FROM deleted;

    RETURN deleted_count;
END
$$;
